---

pgha_etcd_initial_cluster: >-
  pg01=http://192.168.80.92:2380,
  pg02=http://192.168.80.93:2380,
  pg03=http://192.168.80.94:2380

pgha_patroni_etcd_hosts:
  - 192.168.80.92:2379
  - 192.168.80.93:2379
  - 192.168.80.94:2379

pgha_patroni_superuser_name: postgres
pgha_patroni_superuser_pass: ""

pgha_patroni_replication_name: replicator
pgha_patroni_replication_pass: ""

pgha_patroni_admin_role_name: admin
pgha_patroni_admin_role_pass: ""
