---

- name: Prep - Traefik | Detect if zone is missing
  ansible.builtin.set_fact:
    docker_services_cf_zone_missing: >-
      {{
        (cloudflare_zone | default('') | string | trim | length == 0)
      }}

- name: Prep - Traefik | Fetch cloudflare_zone from Infisical
  when: docker_services_cf_zone_missing | bool
  ansible.builtin.include_tasks: >-
    {{ role_path }}/tasks/sub_tasks/prep/infisical/_fetch.yml
  vars:
    infisical_fail_on_empty: true
    infisical_flatten: true
    secrets_map:
      - var: cloudflare_zone
        path: "/Cloudflare"
        name: ZONE

- name: Prep - Traefik | Render dynamic file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/configs/proxy/traefik/dynamic_template.yml.j2"
    dest: >-
      {{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/traefik/dynamic/{{ docker_services_svc.name }}-dynamic.yml
    owner: "1000"
    group: "1000"
    mode: "0644"
    force: true
  vars:
    tr_router_name: "{{ docker_services_svc.name }}"
    tr_exposure: "{{ docker_services_svc.traefik.exposure | default('public') }}"
    tr_private: "{{ tr_exposure == 'private' }}"
    tr_entrypoint: >-
      {{
        docker_services_svc.traefik.entrypoint
        | default(
            'https_private' if tr_private else 'https',
            true
          )
      }}
    tr_zone: >-
      {{
        docker_services_svc.traefik.zone
        | default(
            (
              'int.' ~ hostvars[docker_services_primary_manager].cloudflare_zone
            )
            if tr_private
            else hostvars[docker_services_primary_manager].cloudflare_zone,
            true
          )
      }}
    tr_address: >-
      {{
        (docker_services_svc.traefik.subdomain | default(docker_services_svc.name, true))
        ~ '.'
        ~ tr_zone
      }}
    tr_port: "{{ (docker_services_svc.traefik.port | default(docker_services_svc.ports.web.target)) | int }}"
    tr_authelia_enable: "{{ (docker_services_svc.traefik.sso | default('')) == 'authelia' }}"
    tr_middleware_chain: >-
      {{
        docker_services_svc.traefik.middleware_chain
        | default(
            (tr_router_name ~ '-private-ui-chain')
            if tr_private
            else (tr_router_name ~ '-ui-chain'),
            true
          )
      }}
    tr_internal_api: "{{ (docker_services_svc.traefik.internal_api | default(false)) | bool }}"
    tr_internal_api_matchers: >-
      {{
        (
          docker_services_svc.traefik.internal_api_rules
          if (
            docker_services_svc.traefik.internal_api_rules is defined
            and docker_services_svc.traefik.internal_api_rules is sequence
            and docker_services_svc.traefik.internal_api_rules is not string
          )
          else []
        )
      }}
    tr_headers_middleware: "{{ docker_services_svc.traefik.headers_middleware | default('secure-headers@file') }}"
    tr_theme_enable: >-
      {{
        (docker_services_svc.traefik.themepark.app | default('')) | length > 0
        and
        (docker_services_svc.traefik.themepark.theme | default('')) | length > 0
      }}
    tr_theme_app: "{{ docker_services_svc.traefik.themepark.app | default('') }}"
    tr_theme_theme: "{{ docker_services_svc.traefik.themepark.theme | default('') }}"
    tr_backend_address: "http://{{ docker_services_svc.traefik.backend_host | default(docker_services_svc.name) }}:{{ tr_port }}"
