---

adminer:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: podman
  tags: [utilities, adminer]
  name: adminer
  ################################
  # IMAGE/PROCESS
  ################################
  image: docker.io/library/adminer:5.4.2
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  infisical:
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    adminer:
      driver: bridge
      external: false
  ports:
    - host_ip: "{{ local_ip }}"
      published: 18080
      target: 8080
      protocol: tcp
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 18080
    backend_mode: host
    backend_host_inventory: "{{ services_controller_host }}"
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: container
    host: "{{ services_controller_host }}"
    execution:
      mode: rootless
      host_user: podman-adminer
  systemd:
    after: [network-online.target]
    restart: on-failure
    restart_sec: 10s
