---

alertmanager:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [monitoring, alertmanager]
  name: alertmanager
  stack: alertmanager
  ################################
  # IMAGE/PROCESS
  ################################
  image: prom/alertmanager:v0.33.1
  user: >-
    {{ hostvars[services_controller_host].container_host_puid }}:{{ hostvars[services_controller_host].container_host_pgid }}
  command:
    - "--config.file=/etc/alertmanager/alertmanager.yml"
    - "--storage.path=/alertmanager"
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
      - var: smtp_email
        path: "/Porkbun"
        name: SMTP_EMAIL
      - var: smtp_host
        path: "/Porkbun"
        name: SMTP_HOST
      - var: smtp_password
        path: "/Porkbun"
        name: SMTP_PASS
        secret:
          name: alertmanager_smtp_password_secret
      - var: smtp_port
        path: "/Porkbun"
        name: SMTP_PORT
      - var: smtp_username
        path: "/Porkbun"
        name: SMTP_USER
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/alertmanager"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/alertmanager/data"
      state: directory
      mode: "0755"
  templates:
    - src: configs/alertmanager.yml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/alertmanager/alertmanager.yml"
      mode: "0644"
      force: true
      no_log: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/alertmanager"
      target: /etc/alertmanager
      read_only: true
    data:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/alertmanager/data"
      target: /alertmanager
      read_only: false
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 9093
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: careful
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
