---

alloy:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [monitoring, alloy]
  name: alloy
  stack: alloy
  ################################
  # IMAGE/PROCESS
  ################################
  image: grafana/alloy:v1.20.1
  user: "0"
  command:
    - "run"
    - "--server.http.listen-addr=0.0.0.0:12345"
    - "--storage.path=/etc/alloy/data"
    - "/etc/alloy/config.alloy"
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    ALLOY_HOST: "{{ '{{.Node.Hostname}}' }}"
    TZ: "{{ timezone }}"
  swarm_configs:
    - name: alloy_config
      src: alloy_config.alloy.j2
      data_is_template: true
  configs:
    - source: alloy_config
      target: /etc/alloy/config.alloy
      mode: "0644"
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  named_volumes:
    state:
      external: false
      name: alloy-state
      driver: local
  volumes:
    data:
      type: volume
      source: state
      target: /etc/alloy/data
      read_only: false
    docker_sock:
      type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
    host_rootfs:
      type: bind
      source: /
      target: /host/rootfs
      read_only: true
    host_proc:
      type: bind
      source: /proc
      target: /host/proc
      read_only: true
    host_sys:
      type: bind
      source: /sys
      target: /host/sys
      read_only: true
    docker_lib:
      type: bind
      source: /var/lib/docker
      target: /var/lib/docker
      read_only: true
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 12345
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: global
    profile: careful
    host: "{{ services_controller_host }}"
    constraints:
      - node.platform.os == linux
