---

authelia:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [proxy, pgsql, authelia]
  stack: authelia
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_controller_host].container_host_puid }}"
    PGID: "{{ hostvars[services_controller_host].container_host_pgid }}"
    UMASK: "022"
  infisical:
    secrets_map:
      - var: authelia_redis_key
        path: "/Authelia"
        name: REDIS_KEY
        secret:
          name: authelia_redis_secret
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: careful
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
  ################################
  # TARGETS (INSTANCES)
  ################################
  targets:
    ################################
    # AUTHELIA-REDIS SERVICE
    ################################
    redis:
      ################################
      # IDENTITY
      ################################
      name: authelia-redis
      ################################
      # IMAGE/PROCESS
      ################################
      image: valkey/valkey:9.1-alpine
      command:
        - sh -c 'valkey-server --requirepass "$$(cat /run/secrets/authelia_redis_secret)"'
      ################################
      # FILESYSTEM
      ################################
      paths:
        - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/authelia/redis"
          state: directory
          mode: "0755"
      volumes:
        config:
          type: bind
          source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/authelia/redis"
          target: /data
          read_only: false
    ################################
    # AUTHELIA SERVICE
    ################################
    main:
      ################################
      # IDENTITY
      ################################
      name: authelia
      ################################
      # IMAGE/PROCESS
      ################################
      image: authelia/authelia:4.39.22
      ################################
      # ENVIRONMENT/SECRETS
      ################################
      environment:
        AUTHELIA_SESSION_SECRET_FILE: /run/secrets/authelia_session_key_secret
        AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /run/secrets/authelia_redis_secret
        AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_key_secret
        AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass_secret
        AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/authelia_jwt_key_secret
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /run/secrets/authelia_oidc_hmac_secret
      env_file:
        - "{{ hostvars[services_controller_host].container_host_appdata_root }}/authelia/.env"
      infisical:
        secrets_map:
          - var: postgres_user
            path: "/Postgres"
            name: USER
          - var: postgres_pass
            path: "/Postgres"
            name: PASS
            secret:
              name: postgres_pass_secret
          - var: authelia_user
            path: "/Authelia"
            name: USER
          - var: authelia_pass
            path: "/Authelia"
            name: PASS
          - var: authelia_display_name
            path: "/Authelia"
            name: DISPLAY_NAME
          - var: authelia_storage_key
            path: "/Authelia"
            name: STORAGE_KEY
            secret:
              name: authelia_storage_key_secret
          - var: authelia_oidc_hmac_secret
            path: "/Authelia"
            name: OIDC_HMAC_SECRET
            secret:
              name: authelia_oidc_hmac_secret
          - var: authelia_oidc_jwks_rsa_private_key
            path: "/Authelia"
            name: OIDC_JWKS_RSA_PRIVATE_KEY
          - var: grafana_oidc_client_secret_digest
            path: "/Authelia"
            name: GRAFANA_OIDC_CLIENT_SECRET_DIGEST
          - var: smtp_email
            path: "/Porkbun"
            name: SMTP_EMAIL
          - var: smtp_host
            path: "/Porkbun"
            name: SMTP_HOST
          - var: smtp_password
            path: "/Porkbun"
            name: SMTP_PASS
          - var: smtp_port
            path: "/Porkbun"
            name: SMTP_PORT
          - var: smtp_sender
            path: "/Porkbun"
            name: SMTP_SENDER
          - var: smtp_username
            path: "/Porkbun"
            name: SMTP_USER
      secrets:
        - authelia_session_key_secret
        - authelia_jwt_key_secret
      application_prepare:
        handler: authelia
      ################################
      # FILESYSTEM
      ################################
      paths:
        - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/authelia"
          state: directory
          mode: "0755"
        - path: "{{ services_log_root }}"
          state: directory
          owner: "0"
          group: "0"
          mode: "0755"
        - path: "{{ services_log_root }}/authelia"
          state: directory
          owner: "0"
          group: "0"
          mode: "0755"
      templates:
        - src: configs/proxy/authelia/config.yml.j2
          dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/authelia/configuration.yml"
          mode: "0660"
          force: true
          no_log: true
        - src: configs/proxy/authelia/users_database.yml.j2
          dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/authelia/users_database.yml"
          mode: "0664"
          force: true
          no_log: true
        - src: configs/proxy/authelia/authelia.env.j2
          dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/authelia/.env"
          mode: "0664"
          force: true
          no_log: true
      volumes:
        config:
          type: bind
          source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/authelia"
          target: /config
          read_only: false
        logs:
          type: bind
          source: "{{ services_log_root }}/authelia"
          target: /config/logs
          read_only: false
      ################################
      # INTEGRATIONS
      ################################
      postgres:
        enable: true
        databases:
          - authelia
