---

autobrr:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [media, pgsql, autobrr]
  name: autobrr
  stack: autobrr
  ################################
  # IMAGE/PROCESS
  ################################
  image: ghcr.io/autobrr/autobrr:v1.80.0
  user: >-
    {{ hostvars[services_controller_host].container_host_puid }}:{{ hostvars[services_controller_host].container_host_pgid }}
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    AUTOBRR__HOST: "0.0.0.0"
    AUTOBRR__PORT: "7474"
    AUTOBRR__LOG_LEVEL: "DEBUG"
    AUTOBRR__CHECK_FOR_UPDATES: "true"
    AUTOBRR__SESSION_SECRET:
      value_from:
        infisical: autobrr_session
    AUTOBRR__DATABASE_TYPE: "postgres"
    AUTOBRR__POSTGRES_HOST: "haproxy"
    AUTOBRR__POSTGRES_PORT: "5432"
    AUTOBRR__POSTGRES_DATABASE: "autobrr"
    AUTOBRR__POSTGRES_USER:
      value_from:
        infisical: postgres_user
    AUTOBRR__POSTGRES_PASS:
      value_from:
        infisical: postgres_pass
    AUTOBRR__POSTGRES_SSLMODE: "disable"
  infisical:
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
      - var: autobrr_session
        path: "/AutoBrr"
        name: SESSION_SECRET
      - var: postgres_user
        path: "/Postgres"
        name: USER
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/autobrr"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/autobrr"
      target: /config
      read_only: false
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 7474
  postgres:
    enable: true
    databases:
      - autobrr
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
