---

autobrr:
  enabled: true
  tags: [apps, media, pgsql, autobrr]
  name: autobrr
  stack: autobrr
  image: ghcr.io/autobrr/autobrr:v1.79.0
  named_networks:
    overlay:
      external: true
  user: >-
    {{ hostvars[docker_services_primary_manager].docker_host_puid }}:{{ hostvars[docker_services_primary_manager].docker_host_pgid }}
  environment:
    TZ: "{{ timezone }}"
    AUTOBRR__HOST: "0.0.0.0"
    AUTOBRR__PORT: "7474"
    AUTOBRR__LOG_LEVEL: "DEBUG"
    AUTOBRR__CHECK_FOR_UPDATES: "true"
    AUTOBRR__SESSION_SECRET: "{{ autobrr_session | default('__INFISICAL__:autobrr_session', true) }}"
    AUTOBRR__DATABASE_TYPE: "postgres"
    AUTOBRR__POSTGRES_HOST: "haproxy"
    AUTOBRR__POSTGRES_PORT: "5432"
    AUTOBRR__POSTGRES_DATABASE: "autobrr"
    AUTOBRR__POSTGRES_USER: "{{ postgres_user | default('__INFISICAL__:postgres_user', true) }}"
    AUTOBRR__POSTGRES_PASS: "{{ postgres_pass | default('__INFISICAL__:postgres_pass', true) }}"
    AUTOBRR__POSTGRES_SSLMODE: "disable"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: autobrr_session
        path: "/AutoBrr"
        name: SESSION_SECRET
      - var: postgres_user
        path: "/Postgres"
        name: USER
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/autobrr"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/autobrr"
      target: /config
      read_only: false
  postgres:
    enable: true
    databases:
      - autobrr
  traefik:
    enable: true
    exposure: private
    port: 7474
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
