---

beszel:
  name: beszel
  stack: beszel
  image: henrygd/beszel:latest
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/beszel"
      state: directory
      mode: "0755"
  volumes:
    data:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/beszel"
      target: /beszel_data
      read_only: false
  traefik:
    enable: true
    exposure: private
    port: 8090
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
