---

blackbox_exporter:
  enabled: true
  tags: [monitoring, blackbox_exporter]
  image: prom/blackbox-exporter:v0.27.0
  name: blackbox-exporter
  stack: blackbox-exporter
  named_networks:
    overlay:
      external: true
  command:
    - "--config.file=/etc/blackbox_exporter/config.yml"
  swarm_configs:
    - name: blackbox_exporter_config
      src: templates/configs/prometheus/blackbox.yml.j2
      data_is_template: true
  configs:
    - source: blackbox_exporter_config
      target: /etc/blackbox_exporter/config.yml
      mode: "0444"
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: careful
    host: "{{ docker_services_unraid_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
