---

crowdsec:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [proxy, crowdsec]
  name: crowdsec
  stack: crowdsec
  ################################
  # IMAGE/PROCESS
  ################################
  image: crowdsecurity/crowdsec:v1.8.1
  user: "0:0"
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik LePresidente/authelia"
    GID: "{{ hostvars[services_controller_host].container_host_pgid }}"
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/crowdsec"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/crowdsec/data"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/crowdsec/config"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/crowdsec/config/acquis.d"
      state: directory
      mode: "0755"
    - path: "{{ services_log_root }}"
      state: directory
      owner: "0"
      group: "0"
      mode: "0755"
    - path: "{{ services_log_root }}/traefik"
      state: directory
      owner: "0"
      group: "0"
      mode: "0755"
    - path: "{{ services_log_root }}/authelia"
      state: directory
      owner: "0"
      group: "0"
      mode: "0755"
  templates:
    - src: configs/crowdsec/acquis.yaml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/crowdsec/config/acquis.yaml"
      owner: "0"
      group: "0"
      mode: "0644"
      force: true
    - src: configs/crowdsec/acquis.d/syslog.yaml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/crowdsec/config/acquis.d/syslog.yaml"
      owner: "0"
      group: "0"
      mode: "0644"
      force: true
    - src: configs/crowdsec/acquis.d/traefik.yaml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/crowdsec/config/acquis.d/traefik.yaml"
      owner: "0"
      group: "0"
      mode: "0644"
      force: true
    - src: configs/crowdsec/acquis.d/authelia.yaml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/crowdsec/config/acquis.d/authelia.yaml"
      owner: "0"
      group: "0"
      mode: "0644"
      force: true
  volumes:
    crowdsec_data:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/crowdsec/data"
      target: /var/lib/crowdsec/data
      read_only: false
    crowdsec_config:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/crowdsec/config"
      target: /etc/crowdsec
      read_only: false
    syslog:
      type: bind
      source: /var/log
      target: /var/log
      read_only: true
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: careful
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
