---

czkawka:
  name: czkawka
  stack: czkawka
  image: jlesage/czkawka:v26.03.1
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    USER_ID: "{{ hostvars[docker_services_unraid_host].docker_host_puid }}"
    GROUP_ID: "{{ hostvars[docker_services_unraid_host].docker_host_pgid }}"
    UMASK: "022"
    DARK_MODE: "1"
    WEB_FILE_MANAGER: "1"
  paths:
    - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/czkawka"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/czkawka"
      target: /config
      read_only: false
    media:
      type: bind
      source: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}"
      target: /storage
      read_only: false
  traefik:
    enable: true
    port: 5800
    sso: authelia
  cloudflare:
    enable: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_unraid_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
