---

czkawka:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [utilities, czkawka]
  name: czkawka
  stack: czkawka
  ################################
  # IMAGE/PROCESS
  ################################
  image: jlesage/czkawka:v26.07.3
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    USER_ID: "{{ hostvars[services_storage_host].container_host_puid }}"
    GROUP_ID: "{{ hostvars[services_storage_host].container_host_pgid }}"
    UMASK: "022"
    DARK_MODE: "1"
    WEB_FILE_MANAGER: "1"
  infisical:
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/czkawka"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/czkawka"
      target: /config
      read_only: false
    media:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_data_root }}"
      target: /storage
      read_only: false
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 5800
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_storage_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
