---

dozzle:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [monitoring, dozzle]
  name: dozzle
  stack: dozzle
  ################################
  # IMAGE/PROCESS
  ################################
  image: amir20/dozzle:v10.6.14
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    DOZZLE_MODE: "swarm"
    DOZZLE_NO_ANALYTICS: "true"
    DOZZLE_ENABLE_ACTIONS: "false"
  infisical:
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  volumes:
    docker_sock:
      type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 8080
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: global
    profile: careful
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.haproxy == true
