---

dozzle:
  enabled: true
  tags: [apps, monitoring, dozzle]
  name: dozzle
  stack: dozzle
  image: amir20/dozzle:v10.6.6
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    DOZZLE_MODE: "swarm"
    DOZZLE_NO_ANALYTICS: "true"
    DOZZLE_ENABLE_ACTIONS: "false"
  volumes:
    docker_sock:
      type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
  traefik:
    enable: true
    exposure: private
    port: 8080
  deploy:
    type: swarm
    mode: global
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.haproxy == true
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
