---

etcd:
  name: etcd
  stack: pg-etcd
  container_name: etcd
  image: quay.io/coreos/etcd:v3.5.27
  network_mode: host
  paths:
    - path: /opt/etcd
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
    - path: /opt/etcd/data
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
  volumes:
    data:
      type: bind
      source: /opt/etcd/data
      target: /var/lib/etcd
      read_only: false
  user: 1000:1000
  targets:
    pg01:
      environment:
        ETCD_NAME: "pg01"
        ETCD_DATA_DIR: "/var/lib/etcd"
        ETCD_LISTEN_CLIENT_URLS: "http://192.168.80.92:2379,http://127.0.0.1:2379"
        ETCD_ADVERTISE_CLIENT_URLS: "http://192.168.80.92:2379"
        ETCD_LISTEN_PEER_URLS: "http://192.168.80.92:2380"
        ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://192.168.80.92:2380"
        ETCD_INITIAL_CLUSTER: "pg01=http://192.168.80.92:2380,pg02=http://192.168.80.93:2380,pg03=http://192.168.80.94:2380"
        ETCD_INITIAL_CLUSTER_STATE: "new"
        ETCD_INITIAL_CLUSTER_TOKEN: "pg-ha-1"
        ETCD_ENABLE_V2: "true"
      deploy:
        type: container
        host: pg01
    pg02:
      environment:
        ETCD_NAME: "pg02"
        ETCD_DATA_DIR: "/var/lib/etcd"
        ETCD_LISTEN_CLIENT_URLS: "http://192.168.80.93:2379,http://127.0.0.1:2379"
        ETCD_ADVERTISE_CLIENT_URLS: "http://192.168.80.93:2379"
        ETCD_LISTEN_PEER_URLS: "http://192.168.80.93:2380"
        ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://192.168.80.93:2380"
        ETCD_INITIAL_CLUSTER: "pg01=http://192.168.80.92:2380,pg02=http://192.168.80.93:2380,pg03=http://192.168.80.94:2380"
        ETCD_INITIAL_CLUSTER_STATE: "new"
        ETCD_INITIAL_CLUSTER_TOKEN: "pg-ha-1"
        ETCD_ENABLE_V2: "true"
      deploy:
        type: container
        host: pg02
    pg03:
      environment:
        ETCD_NAME: "pg03"
        ETCD_DATA_DIR: "/var/lib/etcd"
        ETCD_LISTEN_CLIENT_URLS: "http://192.168.80.94:2379,http://127.0.0.1:2379"
        ETCD_ADVERTISE_CLIENT_URLS: "http://192.168.80.94:2379"
        ETCD_LISTEN_PEER_URLS: "http://192.168.80.94:2380"
        ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://192.168.80.94:2380"
        ETCD_INITIAL_CLUSTER: "pg01=http://192.168.80.92:2380,pg02=http://192.168.80.93:2380,pg03=http://192.168.80.94:2380"
        ETCD_INITIAL_CLUSTER_STATE: "new"
        ETCD_INITIAL_CLUSTER_TOKEN: "pg-ha-1"
        ETCD_ENABLE_V2: "true"
      deploy:
        type: container
        host: pg03
