---

gitea:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [utilities, pgsql, gitea]
  name: gitea
  stack: gitea
  ################################
  # IMAGE/PROCESS
  ################################
  image: gitea/gitea:1.26.4
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    USER_UID: "{{ hostvars[services_controller_host].container_host_puid }}"
    USER_GID: "{{ hostvars[services_controller_host].container_host_pgid }}"
    UMASK: "022"
  env_file:
    - "{{ hostvars[services_controller_host].container_host_appdata_root }}/gitea/.env"
  infisical:
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
      - var: postgres_user
        path: "/Postgres"
        name: USER
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/gitea"
      state: directory
      mode: "0755"
  templates:
    - src: configs/gitea.env.j2
      no_log: true
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/gitea/.env"
      mode: "0664"
      force: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/gitea"
      target: /data
      read_only: false
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 3000
  postgres:
    enable: true
    databases:
      - gitea
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: careful
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
