---

gotify:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [monitoring, pgsql, gotify]
  name: gotify
  stack: gotify
  ################################
  # IMAGE/PROCESS
  ################################
  image: gotify/server:3.0.0
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_controller_host].container_host_puid }}"
    PGID: "{{ hostvars[services_controller_host].container_host_pgid }}"
  env_file:
    - "{{ hostvars[services_controller_host].container_host_appdata_root }}/gotify/.env"
  infisical:
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
      - var: postgres_user
        path: "/Postgres"
        name: USER
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/gotify"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/gotify/images"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/gotify/plugins"
      state: directory
      mode: "0755"
  templates:
    - src: configs/gotify.env.j2
      no_log: true
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/gotify/.env"
      mode: "0664"
      force: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/gotify"
      target: /app/data
      read_only: false
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 80
  postgres:
    enable: true
    databases:
      - gotify
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: careful
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
