---

grafana:
  enabled: true
  runtime: docker
  tags: [monitoring, grafana]
  name: grafana
  stack: grafana

  image: grafana/grafana:13.1.0-ubuntu
  user: "0"

  environment:
    TZ: "{{ timezone }}"
    GF_SECURITY_ADMIN_USER__FILE: /run/secrets/grafana_admin_user_secret
    GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_pass_secret
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE: /run/secrets/grafana_oidc_client_secret
  env_file:
    - "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/.env"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: grafana_user
        path: "/Grafana"
        name: USER
      - var: grafana_pass
        path: "/Grafana"
        name: PASS
      - var: grafana_oidc_client_secret
        path: "/Grafana"
        name: OIDC_CLIENT_SECRET
        secret:
          name: grafana_oidc_client_secret
      - var: cloudflare_zone
        path: "/Cloudflare"
        name: ZONE
  secrets:
    - grafana_admin_user_secret
    - grafana_admin_pass_secret

  named_networks:
    overlay:
      external: true

  paths:
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/provisioning/datasources"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/provisioning/dashboards"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/dashboards"
      state: directory
      mode: "0755"
  templates:
    - src: configs/grafana/provisioning/datasources/prometheus.yml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/provisioning/datasources/prometheus.yml"
      mode: "0644"
      force: true
    - src: configs/grafana/provisioning/dashboards/dashboards.yml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/provisioning/dashboards/dashboards.yml"
      mode: "0644"
      force: true
    - src: configs/grafana/dashboards/authelia-community-dashboard.json.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/dashboards/authelia-community-dashboard.json"
      mode: "0644"
      force: true
    - src: configs/grafana/dashboards/haproxy-postgres-overview.json.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/dashboards/haproxy-postgres-overview.json"
      mode: "0644"
      force: true
    - src: configs/grafana/dashboards/homelab-overview.json.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/dashboards/homelab-overview.json"
      mode: "0644"
      force: true
    - src: configs/grafana/dashboards/traefik-official-standalone-dashboard.json.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/dashboards/traefik-official-standalone-dashboard.json"
      mode: "0644"
      force: true
    - src: configs/grafana/dashboards/node-exporter-full.json.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/dashboards/node-exporter-full.json"
      mode: "0644"
      force: true
    - src: configs/grafana/grafana.env.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/.env"
      mode: "0664"
      force: true
      no_log: true
  volumes:
    data:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana"
      target: /var/lib/grafana
      read_only: false
    provisioning:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/provisioning"
      target: /etc/grafana/provisioning
      read_only: true
    dashboards:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/grafana/dashboards"
      target: /var/lib/grafana/dashboards
      read_only: true

  traefik:
    enable: true
    exposure: private
    port: 3000

  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: careful
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
