---

haproxy:
  enabled: true
  runtime: docker
  tags: [haproxy]
  name: haproxy
  stack: haproxy

  image: haproxy:3.4-alpine

  swarm_configs:
    - name: haproxy_cfg
      src: templates/configs/haproxy.cfg.j2
      data_is_template: true
  configs:
    - source: haproxy_cfg
      target: /usr/local/etc/haproxy/haproxy.cfg
      mode: "0444"
  settings:
    haproxy_maxconn: 4096
    haproxy_timeout_connect: 5s
    haproxy_timeout_client: 4h
    haproxy_timeout_server: 4h
    haproxy_timeout_check: 5s
    haproxy_retries: 3
    haproxy_prometheus_port: 8405

  named_networks:
    overlay:
      external: true
  ports:
    postgres:
      published: 5432
      target: 5432
      mode: host

  deploy:
    type: swarm
    mode: global
    profile: careful
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.haproxy == true
