---

homepage:
  enabled: true
  tags: [monitoring, homepage]
  name: homepage
  stack: homepage
  image: ghcr.io/gethomepage/homepage:v1.13.2
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[docker_services_primary_manager].docker_host_puid }}"
    PGID: "{{ hostvars[docker_services_primary_manager].docker_host_pgid }}"
    UMASK: "022"
  env_file:
    - "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/.env"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: autobrr_api
        path: "/AutoBrr"
        name: API
      - var: bazarr_api
        path: "/Bazarr"
        name: API
      - var: cloudflare_zone
        path: "/Cloudflare"
        name: ZONE
      - var: grafana_user
        path: "/Grafana"
        name: USER
      - var: grafana_pass
        path: "/Grafana"
        name: PASS
      - var: seerr_api
        path: "/Seerr"
        name: API
      - var: lidarr_api
        path: "/Lidarr"
        name: API
      - var: ombi_api
        path: "/Ombi"
        name: API
      - var: plex_token
        path: "/Plex"
        name: TOKEN
      - var: portainer_token
        path: "/Portainer"
        name: HOMEPAGE_TOKEN
      - var: prowlarr_api
        path: "/Prowlarr"
        name: API
      - var: qui_downloads_token
        path: "/HomePage"
        name: QUI_DOWNLOADS_TOKEN
      - var: qui_seeds_token
        path: "/HomePage"
        name: QUI_SEEDS_TOKEN
      - var: radarr_api
        path: "/Radarr"
        name: API
      - var: radarr_4k_api
        path: "/Radarr-4K"
        name: API
      - var: sabnzbd_api
        path: "/SABnzbd"
        name: API
      - var: sonarr_api
        path: "/Sonarr"
        name: API
      - var: sonarr_4k_api
        path: "/Sonarr-4K"
        name: API
      - var: stash_api
        path: "/Stash"
        name: API
      - var: tautulli_api
        path: "/Tautulli"
        name: API
      - var: technitium_token
        path: "/HomePage"
        name: TECHNITIUM_TOKEN
      - var: unifi_user
        path: "/Unifi"
        name: USER
      - var: unifi_pass
        path: "/Unifi"
        name: PASS
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/images"
      state: directory
      mode: "0755"
  copies:
    - src: files/earth-rise-2.jpg
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/images/earth-rise-2.jpg"
      mode: "0755"
      force: false
      wait: true
      wait_timeout: 30
  templates:
    - src: configs/homepage/docker.yaml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/docker.yaml"
      mode: "0664"
      force: true
    - src: configs/homepage/services.yaml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/services.yaml"
      mode: "0664"
      force: true
    - src: configs/homepage/settings.yaml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/settings.yaml"
      mode: "0664"
      force: true
    - src: configs/homepage/bookmarks.yaml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/bookmarks.yaml"
      mode: "0664"
      force: true
    - src: configs/homepage/widgets.yaml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/widgets.yaml"
      mode: "0664"
      force: true
    - src: configs/homepage/custom.css.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/custom.css"
      mode: "0664"
      force: true
    - src: configs/homepage/homepage.env.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/.env"
      mode: "0664"
      force: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage"
      target: /app/config
      read_only: false
    images:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/homepage/images"
      target: /app/public/images
      read_only: true
  traefik:
    enable: true
    exposure: private
    port: 3000
  deploy:
    type: swarm
    mode: replicated
    profile: standard
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
