---

kometa:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [plex, kometa]
  name: kometa
  stack: kometa
  ################################
  # IMAGE/PROCESS
  ################################
  image: kometateam/kometa:v2.4.7
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_plex_host].container_host_puid }}"
    PGID: "{{ hostvars[services_plex_host].container_host_pgid }}"
    UMASK: "022"
  infisical:
    secrets_map:
      - var: mdblist_api
        path: "/Kometa"
        name: MDBLIST_API
      - var: tmdb_api
        path: "/Kometa"
        name: TMDB_API
      - var: trakt_id
        path: "/Kometa"
        name: TRAKT_ID
      - var: trakt_secret
        path: "/Kometa"
        name: TRAKT_SECRET
      - var: radarr_api
        path: "/Radarr"
        name: API
      - var: sonarr_api
        path: "/Sonarr"
        name: API
      - var: tautulli_api
        path: "/Tautulli"
        name: API
      - var: plex_token
        path: "/Plex"
        name: TOKEN
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_plex_host].container_host_appdata_root }}/kometa"
      state: directory
      mode: "0755"
  templates:
    - src: configs/kometa.yml.j2
      no_log: true
      dest: "{{ hostvars[services_plex_host].container_host_appdata_root }}/kometa/config.yml"
      mode: "0664"
      force: false
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_plex_host].container_host_appdata_root }}/kometa"
      target: /config
      read_only: false
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_plex_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_plex_host
