---

lidarr:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [arrs, pgsql, lidarr]
  name: lidarr
  stack: lidarr
  ################################
  # IMAGE/PROCESS
  ################################
  image: ghcr.io/hotio/lidarr:release-3.1.0.4875
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_storage_host].container_host_puid }}"
    PGID: "{{ hostvars[services_storage_host].container_host_pgid }}"
    UMASK: "022"
    LIDARR__APP__INSTANCENAME: "Lidarr"
    LIDARR__SERVER__PORT: "8686"
    LIDARR__AUTH__METHOD: "External"
    FILE__LIDARR__AUTH__APIKEY: /run/secrets/lidarr_api_secret
    LIDARR__POSTGRES__HOST: "haproxy"
    LIDARR__POSTGRES__PORT: "5432"
    FILE__LIDARR__POSTGRES__USER: /run/secrets/postgres_user_secret
    FILE__LIDARR__POSTGRES__PASSWORD: /run/secrets/postgres_pass_secret
    LIDARR__POSTGRES__MAINDB: "lidarr-main"
    LIDARR__POSTGRES__LOGDB: "lidarr-log"
    TP_SCHEME: "http"
    TP_DOMAIN: "{{ hostvars[services_controller_host].local_ip }}:8089"
    TP_HOTIO: "true"
    TP_THEME: "hotline"
  infisical:
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
      - var: lidarr_api
        path: "/Lidarr"
        name: API
        secret:
          name: lidarr_api_secret
      - var: postgres_user
        path: "/Postgres"
        name: USER
        secret:
          name: postgres_user_secret
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
        secret:
          name: postgres_pass_secret
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/lidarr"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_storage_host].container_host_data_root }}/media/music"
      state: directory
      mode: "0755"
  copies:
    - src: files/themepark/98-themepark-lidarr
      dest: "{{ hostvars[services_storage_host].container_host_appdata_root }}/lidarr/98-themepark-lidarr"
      mode: "0755"
      force: false
      wait: true
      wait_timeout: 30
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/lidarr"
      target: /config
      read_only: false
    media:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_data_root }}"
      target: /data
      read_only: false
    themepark:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/lidarr/98-themepark-lidarr"
      target: /etc/cont-init.d/98-themepark
      read_only: false
  ################################
  # HEALTH
  ################################
  healthcheck:
    test:
      - "CMD-SHELL"
      - "touch /data/media/music/.healthcheck && rm -f /data/media/music/.healthcheck || exit 1"
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 8686
  themepark:
    app: lidarr
    theme: hotline
  postgres:
    enable: true
    databases:
      - lidarr-main
      - lidarr-log
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_storage_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
