---

obsidian:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [media, obsidian]
  name: obsidian
  stack: obsidian
  ################################
  # IMAGE/PROCESS
  ################################
  image: lscr.io/linuxserver/obsidian:v1.13.7-ls143
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_controller_host].container_host_puid }}"
    PGID: "{{ hostvars[services_controller_host].container_host_pgid }}"
    UMASK: "022"
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/obsidian"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/obsidian/vault"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/obsidian/vault/posts"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/obsidian"
      target: /config
      read_only: false
  shm_size: 1gb
  shm_tmpfs_size: 1073741824
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 3000
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
