---

obsidian:
  name: obsidian
  stack: obsidian
  image: lscr.io/linuxserver/obsidian:v1.12.7-ls121
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD"
      - "curl"
      - "--fail"
      - "http://localhost:1314"
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[docker_services_primary_manager].docker_host_puid }}"
    PGID: "{{ hostvars[docker_services_primary_manager].docker_host_pgid }}"
    UMASK: "022"
    CUSTOM_PORT: "1314"
    CUSTOM_HTTPS_PORT: "1315"
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/obsidian"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/obsidian/vault"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/obsidian/vault/posts"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/obsidian"
      target: /config
      read_only: false
  shm_size: 2gb
  shm_tmpfs_size: 1073741824
  traefik:
    enable: true
    port: 1314
    sso: authelia
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
