---

plex:
  enabled: true
  runtime: docker
  tags: [plex, plex_server]
  name: plex
  stack: plex

  image: lscr.io/linuxserver/plex:1.43.2

  environment:
    PUID: "{{ hostvars[services_plex_host].container_host_puid | string }}"
    PGID: "{{ hostvars[services_plex_host].container_host_pgid | string }}"
    TZ: "{{ timezone }}"
    VERSION: "docker"
    PLEX_CLAIM: "{{ plex_claim_code | default(omit) }}"
    ADVERTISE_IP: "http://{{ hostvars[services_plex_host].local_ip }}:32400/"
    TP_SCHEME: "http"
    DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:plex"
    TP_DOMAIN: "{{ hostvars[services_controller_host].local_ip }}:8089"
    TP_THEME: "hotline"

  application_prepare:
    handler: plex
    bootstrap:
      enabled: true

  named_networks:
    overlay:
      external: true
  ports:
    web:
      published: 32400
      target: 32400
      mode: host
    dlna_udp:
      published: 1900
      target: 1900
      protocol: udp
      mode: host
    dlna_tcp:
      published: 32469
      target: 32469
      mode: host
    avahi:
      published: 5353
      target: 5353
      protocol: udp
      mode: host
    roku:
      published: 8324
      target: 8324
      mode: host
    gdm_10:
      published: 32410
      target: 32410
      protocol: udp
      mode: host
    gdm_12:
      published: 32412
      target: 32412
      protocol: udp
      mode: host
    gdm_13:
      published: 32413
      target: 32413
      protocol: udp
      mode: host
    gdm_14:
      published: 32414
      target: 32414
      protocol: udp
      mode: host

  paths:
    - path: "{{ hostvars[services_plex_host].container_host_appdata_root }}/plex"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_plex_host].container_host_appdata_root }}/plex/Library"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_plex_host].container_host_appdata_root }}/plex/Library/Application Support"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_plex_host].container_host_appdata_root }}/plex/Library/Application Support/Plex Media Server"
      state: directory
      mode: "0755"
    - path: >-
        {{ hostvars[services_plex_host].container_host_appdata_root
        }}/plex/Library/Application Support/Plex Media Server/Plug-ins
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_plex_host].container_host_appdata_root }}/plex/Library/Logs"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_plex_host].container_host_appdata_root }}/plex/Library/Logs/Plex Media Server"
      state: directory
      mode: "0755"
  named_volumes:
    media_nfs:
      external: false
      name: media_nfs
      driver: local
      driver_opts:
        type: nfs
        o: "addr={{ hostvars[services_storage_host].local_ip }},rw,nfsvers=4.2"
        device: ":{{ hostvars[services_storage_host].container_host_data_root }}/media"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_plex_host].container_host_appdata_root }}/plex"
      target: /config
      read_only: false
    transcode:
      type: bind
      source: /dev/shm
      target: /transcode
      read_only: false
    media:
      type: volume
      source: media_nfs
      target: /data/media
      read_only: false

  devices:
    - /dev/dri:/dev/dri

  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_plex_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_plex_host
