---

prometheus:
  name: prometheus
  stack: prometheus
  image: prom/prometheus:v3.11.3
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD"
      - "wget"
      - "--spider"
      - "-q"
      - "http://127.0.0.1:9090/-/ready"
  command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.enable-remote-write-receiver"
  user: >-
    {{ hostvars[docker_services_primary_manager].docker_host_puid }}:{{ hostvars[docker_services_primary_manager].docker_host_pgid }}
  environment:
    TZ: "{{ timezone }}"
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/data"
      state: directory
      mode: "0755"
  templates:
    - src: configs/prometheus.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/prometheus.yml"
      mode: "0644"
      force: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus"
      target: /etc/prometheus
      read_only: true
    data:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/data"
      target: /prometheus
      read_only: false
  traefik:
    enable: true
    exposure: private
    port: 9090
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
