---

prometheus:
  enabled: true
  tags: [monitoring, prometheus]
  name: prometheus
  stack: prometheus
  image: prom/prometheus:v3.13.1
  named_networks:
    overlay:
      external: true
  command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.enable-remote-write-receiver"
  user: >-
    {{ hostvars[docker_services_primary_manager].docker_host_puid }}:{{ hostvars[docker_services_primary_manager].docker_host_pgid }}
  environment:
    TZ: "{{ timezone }}"
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/data"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/rules"
      state: directory
      mode: "0755"
  templates:
    - src: configs/prometheus/prometheus.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/prometheus.yml"
      mode: "0644"
      force: true
    - src: configs/prometheus/rules/infrastructure.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/rules/infrastructure.yml"
      mode: "0644"
      force: true
    - src: configs/prometheus/rules/applications.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/rules/applications.yml"
      mode: "0644"
      force: true
    - src: configs/prometheus/rules/node-exporter.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/rules/node-exporter.yml"
      mode: "0644"
      force: true
    - src: configs/prometheus/rules/dns.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/rules/dns.yml"
      mode: "0644"
      force: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus"
      target: /etc/prometheus
      read_only: true
    data:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/prometheus/data"
      target: /prometheus
      read_only: false
  traefik:
    enable: true
    exposure: private
    port: 9090
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: careful
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
