---

prowlarr:
  name: prowlarr
  stack: prowlarr
  image: ghcr.io/hotio/prowlarr:release-2.3.5.5327
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD"
      - "curl"
      - "--fail"
      - "http://localhost:9696"
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[docker_services_unraid_host].docker_host_puid }}"
    PGID: "{{ hostvars[docker_services_unraid_host].docker_host_pgid }}"
    UMASK: "022"
    PROWLARR__APP__INSTANCENAME: "Prowlarr"
    PROWLARR__SERVER__PORT: "9696"
    PROWLARR__AUTH__METHOD: "External"
    FILE__PROWLARR__AUTH__APIKEY: /run/secrets/prowlarr_api_secret
    PROWLARR__POSTGRES__HOST: "haproxy"
    PROWLARR__POSTGRES__PORT: "5433"
    FILE__PROWLARR__POSTGRES__USER: /run/secrets/postgres_user_secret
    FILE__PROWLARR__POSTGRES__PASSWORD: /run/secrets/postgres_pass_secret
    PROWLARR__POSTGRES__MAINDB: "prowlarr-main"
    PROWLARR__POSTGRES__LOGDB: "prowlarr-log"
    TP_SCHEME: "http"
    TP_DOMAIN: "{{ hostvars[docker_services_primary_manager].local_ip }}:8089"
    TP_HOTIO: "true"
    TP_THEME: "hotline"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: prowlarr_api
        path: "/Prowlarr"
        name: API
        docker_secret: prowlarr_api_secret
      - var: postgres_user
        path: "/Postgres"
        name: USER
        docker_secret: postgres_user_secret
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
        docker_secret: postgres_pass_secret
  secrets:
    - prowlarr_api_secret
    - postgres_user_secret
    - postgres_pass_secret
  paths:
    - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/prowlarr"
      state: directory
      mode: "0755"
  copies:
    - src: files/themepark/98-themepark-prowlarr
      dest: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/prowlarr/98-themepark-prowlarr"
      mode: "0755"
      force: false
      wait: true
      wait_timeout: 30
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/prowlarr"
      target: /config
      read_only: false
    media:
      type: bind
      source: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}"
      target: /data
      read_only: false
    themepark:
      type: bind
      source: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/prowlarr/98-themepark-prowlarr"
      target: /etc/cont-init.d/98-themepark
      read_only: false
  traefik:
    enable: true
    exposure: private
    port: 9696
  themepark:
    app: prowlarr
    theme: hotline
  postgres:
    enable: true
    databases:
      - prowlarr-main
      - prowlarr-log
    clean_sqlite: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_unraid_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
