---

prowlarr:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [arrs, pgsql, prowlarr]
  name: prowlarr
  stack: prowlarr
  ################################
  # IMAGE/PROCESS
  ################################
  image: ghcr.io/hotio/prowlarr:release-2.4.0.5397
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_storage_host].container_host_puid }}"
    PGID: "{{ hostvars[services_storage_host].container_host_pgid }}"
    UMASK: "022"
    PROWLARR__APP__INSTANCENAME: "Prowlarr"
    PROWLARR__SERVER__PORT: "9696"
    PROWLARR__AUTH__METHOD: "External"
    FILE__PROWLARR__AUTH__APIKEY: /run/secrets/prowlarr_api_secret
    PROWLARR__POSTGRES__HOST: "haproxy"
    PROWLARR__POSTGRES__PORT: "5432"
    FILE__PROWLARR__POSTGRES__USER: /run/secrets/postgres_user_secret
    FILE__PROWLARR__POSTGRES__PASSWORD: /run/secrets/postgres_pass_secret
    PROWLARR__POSTGRES__MAINDB: "prowlarr-main"
    PROWLARR__POSTGRES__LOGDB: "prowlarr-log"
    TP_SCHEME: "http"
    TP_DOMAIN: "{{ hostvars[services_controller_host].local_ip }}:8089"
    TP_HOTIO: "true"
    TP_THEME: "hotline"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
      - var: prowlarr_api
        path: "/Prowlarr"
        name: API
        secret:
          name: prowlarr_api_secret
      - var: postgres_user
        path: "/Postgres"
        name: USER
        secret:
          name: postgres_user_secret
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
        secret:
          name: postgres_pass_secret
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/prowlarr"
      state: directory
      mode: "0755"
  copies:
    - src: files/themepark/98-themepark-prowlarr
      dest: "{{ hostvars[services_storage_host].container_host_appdata_root }}/prowlarr/98-themepark-prowlarr"
      mode: "0755"
      force: false
      wait: true
      wait_timeout: 30
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/prowlarr"
      target: /config
      read_only: false
    media:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_data_root }}"
      target: /data
      read_only: false
    themepark:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/prowlarr/98-themepark-prowlarr"
      target: /etc/cont-init.d/98-themepark
      read_only: false
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 9696
  themepark:
    app: prowlarr
    theme: hotline
  postgres:
    enable: true
    databases:
      - prowlarr-main
      - prowlarr-log
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_storage_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
