---

qbittorrent:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [torrents, qbittorrent]
  ################################
  # IMAGE/PROCESS
  ################################
  image: ghcr.io/hotio/qbittorrent:release-v5.2.2
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    PUID: "{{ hostvars[services_storage_host].container_host_puid }}"
    PGID: "{{ hostvars[services_storage_host].container_host_pgid }}"
    TZ: "{{ timezone }}"
    FILE__VPN_PIA_USER: /run/secrets/qbittorrent_pia_user_secret
    FILE__VPN_PIA_PASS: /run/secrets/qbittorrent_pia_pass_secret
  infisical:
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
      - var: qbittorrent_pia_user
        path: "/PIA"
        name: USER
        secret:
          name: qbittorrent_pia_user_secret
      - var: qbittorrent_pia_pass
        path: "/PIA"
        name: PASS
        secret:
          name: qbittorrent_pia_pass_secret
  application_prepare:
    handler: qbittorrent
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # DEVICES/SECURITY
  ################################
  devices:
    - "/dev/net/tun:/dev/net/tun"
  cap_add:
    - NET_ADMIN
  sysctls:
    net.ipv4.conf.all.src_valid_mark: "1"
    net.ipv6.conf.all.disable_ipv6: "1"
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_storage_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
  ################################
  # TARGETS (INSTANCES)
  ################################
  targets:
    ################################
    # QBIT MAIN SERVICE
    ################################
    downloads:
      ################################
      # IDENTITY
      ################################
      tags: [qbittorrent-main]
      name: qbittorrent
      stack: qbittorrent
      hostname: qbittorrent.internal
      ################################
      # ENVIRONMENT/SECRETS
      ################################
      env_file:
        - /opt/stacks/qbittorrent.env
      infisical:
        secrets_map:
          - var: qbittorrent_user
            path: "/qBittorrent"
            name: USER
          - var: qbittorrent_pass
            path: "/qBittorrent"
            name: PASS
      swarm_env_templates:
        - src: configs/qbittorrent/qBittorrent.env.j2
          dest: /opt/stacks/qbittorrent.env
          owner: "{{ hostvars[services_storage_host].container_host_puid }}"
          group: "{{ hostvars[services_storage_host].container_host_pgid }}"
          mode: "0600"
          force: true
      ################################
      # FILESYSTEM
      ################################
      paths:
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent/config"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent/wireguard"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/completed"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/incoming"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/watched"
          state: directory
          mode: "0755"
      templates:
        - src: configs/qbittorrent/qBittorrent.conf.j2
          dest: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent/config/qBittorrent.conf"
          mode: "0664"
          force: true
          no_log: true
      volumes:
        config:
          type: bind
          source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent"
          target: /config
          read_only: false
        media:
          type: bind
          source: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents"
          target: /data/torrents
          read_only: false
      ################################
      # HEALTH
      ################################
      healthcheck:
        test:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - "http://127.0.0.1:8090/"
      ################################
      # INTEGRATIONS
      ################################
      traefik:
        enable: true
        exposure: private
        port: 8090
    ################################
    # QBIT CROSS-SEED SERVICE
    ################################
    seeds:
      ################################
      # IDENTITY
      ################################
      tags: [qbittorrent-xs]
      name: qbittorrent-xs
      stack: qbittorrent-xs
      hostname: qbittorrent-xs.internal
      ################################
      # ENVIRONMENT/SECRETS
      ################################
      env_file:
        - /opt/stacks/qbittorrent-xs.env
      infisical:
        secrets_map:
          - var: qbittorrent_xs_user
            path: "/qBittorrent-XS"
            name: USER
          - var: qbittorrent_xs_pass
            path: "/qBittorrent-XS"
            name: PASS
      swarm_env_templates:
        - src: configs/qbittorrent/qBittorrent-xs.env.j2
          dest: /opt/stacks/qbittorrent-xs.env
          owner: "{{ hostvars[services_storage_host].container_host_puid }}"
          group: "{{ hostvars[services_storage_host].container_host_pgid }}"
          mode: "0600"
          force: true
      ################################
      # FILESYSTEM
      ################################
      paths:
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-xs"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-xs/config"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-xs/wireguard"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/seeds"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/seeds/completed"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/seeds/incoming"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/seeds/watched"
          state: directory
          mode: "0755"
      templates:
        - src: configs/qbittorrent/qBittorrent-xs.conf.j2
          dest: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-xs/config/qBittorrent.conf"
          mode: "0664"
          force: true
          no_log: true
      volumes:
        config:
          type: bind
          source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-xs"
          target: /config
          read_only: false
        media:
          type: bind
          source: "{{ hostvars[services_storage_host].container_host_data_root }}/seeds"
          target: /data/seeds
          read_only: false
      ################################
      # HEALTH
      ################################
      healthcheck:
        test:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - "http://127.0.0.1:8091/"
      ################################
      # INTEGRATIONS
      ################################
      traefik:
        enable: true
        exposure: private
        port: 8091
