---

qbittorrent:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [torrents, qbittorrent]
  ################################
  # IMAGE/PROCESS
  ################################
  image: ghcr.io/hotio/qbittorrent:release-v5.2.3
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    PUID: "{{ hostvars[services_storage_host].container_host_puid }}"
    PGID: "{{ hostvars[services_storage_host].container_host_pgid }}"
    TZ: "{{ timezone }}"
    FILE__VPN_PIA_USER: /run/secrets/qbittorrent_pia_user_secret
    FILE__VPN_PIA_PASS: /run/secrets/qbittorrent_pia_pass_secret
  infisical:
    secrets_map:
      - var: qbittorrent_pia_user
        path: "/PIA"
        name: USER
        secret:
          name: qbittorrent_pia_user_secret
      - var: qbittorrent_pia_pass
        path: "/PIA"
        name: PASS
        secret:
          name: qbittorrent_pia_pass_secret
  application_prepare:
    handler: qbittorrent
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents"
      state: directory
      mode: "0755"
  ################################
  # DEVICES/SECURITY
  ################################
  devices:
    - "/dev/net/tun:/dev/net/tun"
  cap_add:
    - NET_ADMIN
  sysctls:
    net.ipv4.conf.all.src_valid_mark: "1"
    net.ipv6.conf.all.disable_ipv6: "1"
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_storage_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
  ################################
  # TARGETS (INSTANCES)
  ################################
  targets:
    ################################
    # ALPHA
    ################################
    alpha:
      ################################
      # IDENTITY
      ################################
      tags: [qbittorrent-alpha]
      name: qbittorrent-alpha
      stack: qbittorrent-alpha
      ################################
      # IMAGE/PROCESS
      ################################
      hostname: qbittorrent-alpha.internal
      ################################
      # ENVIRONMENT/SECRETS
      ################################
      env_file:
        - /opt/stacks/qbittorrent-alpha.env
      infisical:
        secrets_map:
          - var: qbittorrent_user
            path: "/qBittorrent-Alpha"
            name: USER
          - var: qbittorrent_pass
            path: "/qBittorrent-Alpha"
            name: PASS
      swarm_env_templates:
        - src: configs/qbittorrent/qBittorrent.env.j2
          dest: /opt/stacks/qbittorrent-alpha.env
          owner: "{{ hostvars[services_storage_host].container_host_puid }}"
          group: "{{ hostvars[services_storage_host].container_host_pgid }}"
          mode: "0600"
          force: true
      ################################
      # FILESYSTEM
      ################################
      paths:
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-alpha"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-alpha/config"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-alpha/wireguard"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/alpha"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/alpha/completed"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/alpha/incoming"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/alpha/watched"
          state: directory
          mode: "0755"
      templates:
        - src: configs/qbittorrent/qBittorrent.conf.j2
          dest: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-alpha/config/qBittorrent.conf"
          mode: "0664"
          force: true
          no_log: true
      volumes:
        config:
          type: bind
          source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-alpha"
          target: /config
          read_only: false
        media:
          type: bind
          source: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/alpha"
          target: /data/torrents/alpha
          read_only: false
      ################################
      # HEALTH
      ################################
      healthcheck:
        test:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - "http://127.0.0.1:8090/"
      ################################
      # INTEGRATIONS
      ################################
      traefik:
        enable: true
        exposure: private
        port: 8090
    ################################
    # BRAVO
    ################################
    bravo:
      ################################
      # IDENTITY
      ################################
      tags: [qbittorrent-bravo]
      name: qbittorrent-bravo
      stack: qbittorrent-bravo
      ################################
      # IMAGE/PROCESS
      ################################
      hostname: qbittorrent-bravo.internal
      ################################
      # ENVIRONMENT/SECRETS
      ################################
      env_file:
        - /opt/stacks/qbittorrent-bravo.env
      infisical:
        secrets_map:
          - var: qbittorrent_user
            path: "/qBittorrent-Bravo"
            name: USER
          - var: qbittorrent_pass
            path: "/qBittorrent-Bravo"
            name: PASS
      swarm_env_templates:
        - src: configs/qbittorrent/qBittorrent.env.j2
          dest: /opt/stacks/qbittorrent-bravo.env
          owner: "{{ hostvars[services_storage_host].container_host_puid }}"
          group: "{{ hostvars[services_storage_host].container_host_pgid }}"
          mode: "0600"
          force: true
      ################################
      # FILESYSTEM
      ################################
      paths:
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-bravo"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-bravo/config"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-bravo/wireguard"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/bravo"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/bravo/completed"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/bravo/incoming"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/bravo/watched"
          state: directory
          mode: "0755"
      templates:
        - src: configs/qbittorrent/qBittorrent.conf.j2
          dest: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-bravo/config/qBittorrent.conf"
          mode: "0664"
          force: true
          no_log: true
      volumes:
        config:
          type: bind
          source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/qbittorrent-bravo"
          target: /config
          read_only: false
        media:
          type: bind
          source: "{{ hostvars[services_storage_host].container_host_data_root }}/torrents/bravo"
          target: /data/torrents/bravo
          read_only: false
      ################################
      # HEALTH
      ################################
      healthcheck:
        test:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - "http://127.0.0.1:8091/"
      ################################
      # INTEGRATIONS
      ################################
      traefik:
        enable: true
        exposure: private
        port: 8091
