---

recyclarr:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [arrs, recyclarr]
  name: recyclarr
  stack: recyclarr
  ################################
  # IMAGE/PROCESS
  ################################
  image: ghcr.io/recyclarr/recyclarr:8.6.0
  user: >-
    {{ hostvars[services_storage_host].container_host_puid }}:{{ hostvars[services_storage_host].container_host_pgid }}
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
  infisical:
    secrets_map:
      - var: radarr_api
        path: "/Radarr"
        name: API
      - var: radarr_4k_api
        path: "/Radarr-4K"
        name: API
      - var: sonarr_api
        path: "/Sonarr"
        name: API
      - var: sonarr_4k_api
        path: "/Sonarr-4K"
        name: API
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/recyclarr"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/recyclarr/configs"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/recyclarr/includes"
      state: directory
      mode: "0755"
  templates:
    - src: configs/recyclarr/secrets.yml.j2
      no_log: true
      dest: "{{ hostvars[services_storage_host].container_host_appdata_root }}/recyclarr/secrets.yml"
      mode: "0664"
      force: true
    - src: configs/recyclarr/config_radarr.yml.j2
      dest: "{{ hostvars[services_storage_host].container_host_appdata_root }}/recyclarr/configs/radarr.yml"
      mode: "0664"
      force: true
    - src: configs/recyclarr/config_sonarr.yml.j2
      dest: "{{ hostvars[services_storage_host].container_host_appdata_root }}/recyclarr/configs/sonarr.yml"
      mode: "0664"
      force: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/recyclarr"
      target: /config
      read_only: false
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_storage_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
