---

scraparr:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [monitoring, scraparr]
  name: scraparr
  stack: scraparr
  ################################
  # IMAGE/PROCESS
  ################################
  image: thegameprofi/scraparr:3.1.0
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_controller_host].container_host_puid }}"
    PGID: "{{ hostvars[services_controller_host].container_host_pgid }}"
    UMASK: "022"
    GENERAL_PORT: "7100"
    BAZARR_URL: >-
      https://bazarr.{{ services_internal_zone }}:{{ services_private_https_port }}
    BAZARR_API_KEY_FILE: /run/secrets/bazarr_api_secret
    BAZARR_ALIAS: "bazarr"
    LIDARR_URL: >-
      https://lidarr.{{ services_internal_zone }}:{{ services_private_https_port }}
    LIDARR_API_KEY_FILE: /run/secrets/lidarr_api_secret
    LIDARR_ALIAS: "lidarr"
    PROWLARR_URL: >-
      https://prowlarr.{{ services_internal_zone }}:{{ services_private_https_port }}
    PROWLARR_API_KEY_FILE: /run/secrets/prowlarr_api_secret
    PROWLARR_ALIAS: "prowlarr"
    RADARR_MAIN_URL: >-
      https://radarr.{{ services_internal_zone }}:{{ services_private_https_port }}
    RADARR_MAIN_API_KEY_FILE: /run/secrets/radarr_api_secret
    RADARR_MAIN_ALIAS: "radarr"
    RADARR_SECONDARY_URL: >-
      https://radarr-4k.{{ services_internal_zone }}:{{ services_private_https_port }}
    RADARR_SECONDARY_API_KEY_FILE: /run/secrets/radarr_4k_api_secret
    RADARR_SECONDARY_ALIAS: "radarr-4k"
    RADARR_WHISPARR_URL: >-
      https://whisparr.{{ services_internal_zone }}:{{ services_private_https_port }}
    RADARR_WHISPARR_API_KEY_FILE: /run/secrets/whisparr_api_secret
    RADARR_WHISPARR_ALIAS: "whisparr"
    SONARR_MAIN_URL: >-
      https://sonarr.{{ services_internal_zone }}:{{ services_private_https_port }}
    SONARR_MAIN_API_KEY_FILE: /run/secrets/sonarr_api_secret
    SONARR_MAIN_ALIAS: "sonarr"
    SONARR_SECONDARY_URL: >-
      https://sonarr-4k.{{ services_internal_zone }}:{{ services_private_https_port }}
    SONARR_SECONDARY_API_KEY_FILE: /run/secrets/sonarr_4k_api_secret
    SONARR_SECONDARY_ALIAS: "sonarr-4k"
  infisical:
    secrets_map:
      - var: lidarr_api
        path: "/Lidarr"
        name: API
        secret:
          name: lidarr_api_secret
      - var: prowlarr_api
        path: "/Prowlarr"
        name: API
        secret:
          name: prowlarr_api_secret
      - var: radarr_api
        path: "/Radarr"
        name: API
        secret:
          name: radarr_api_secret
      - var: radarr_4k_api
        path: "/Radarr-4K"
        name: API
        secret:
          name: radarr_4k_api_secret
      - var: sonarr_api
        path: "/Sonarr"
        name: API
        secret:
          name: sonarr_api_secret
      - var: sonarr_4k_api
        path: "/Sonarr-4K"
        name: API
        secret:
          name: sonarr_4k_api_secret
      - var: whisparr_api
        path: "/Whisparr"
        name: API
        secret:
          name: whisparr_api_secret
  secrets:
    - bazarr_api_secret
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
