---

sportarr:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [arrs, sportarr]
  name: sportarr
  stack: sportarr
  ################################
  # IMAGE/PROCESS
  ################################
  image: sportarr/sportarr:4.0.1016.1096
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_storage_host].container_host_puid }}"
    PGID: "{{ hostvars[services_storage_host].container_host_pgid }}"
    UMASK: "022"
    Sportarr__Database__Provider: "postgres"
    Sportarr__Database__Host: "haproxy"
    Sportarr__Database__Port: "5432"
    Sportarr__Database__Name: "sportarr"
    FILE__Sportarr__Database__Username: /run/secrets/postgres_user_secret
    FILE__Sportarr__Database__Password: /run/secrets/postgres_pass_secret
  infisical:
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
      - var: postgres_user
        path: "/Postgres"
        name: USER
        secret:
          name: postgres_user_secret
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
        secret:
          name: postgres_pass_secret
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/sportarr"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/sportarr/config"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_storage_host].container_host_data_root }}/media/sport"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/sportarr/config"
      target: /config
      read_only: false
    media:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_data_root }}"
      target: /data
      read_only: false
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 1867
  postgres:
    enable: true
    databases:
      - sportarr
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_storage_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
