---

stash:
  name: stash
  stack: stash
  image: ghcr.io/hotio/stash:release-v0.31.1
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD-SHELL"
      - "touch /data/media/adult/.healthcheck && rm -f /data/media/adult/.healthcheck || exit 1"
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[docker_services_unraid_host].docker_host_puid }}"
    PGID: "{{ hostvars[docker_services_unraid_host].docker_host_pgid }}"
    UMASK: "022"
    STASH_CONFIG_FILE: "/config/config.yml"
    STASH_METADATA: "/config/metadata"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: stash_api
        path: "/Stash"
        name: API
      - var: fansdb_api
        path: "/Stash"
        name: FANSDB_API
      - var: pmv_api
        path: "/Stash"
        name: PMV_API
      - var: porndb_api
        path: "/Stash"
        name: PORNDB_API
      - var: stashdb_api
        path: "/Stash"
        name: STASHDB_API
  paths:
    - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/stash"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/stash/metadata"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/stash/cache"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/stash/blobs"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/stash/generated"
      state: directory
      mode: "0755"
  templates:
    - src: configs/stash.yml.j2
      dest: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/stash/config.yml"
      mode: "0664"
      force: false
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/stash"
      target: /config
      read_only: false
    media:
      type: bind
      source: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}"
      target: /data
      read_only: false
  traefik:
    enable: true
    exposure: private
    port: 9999
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_unraid_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
