---

syncthing:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [utilities, syncthing]
  name: syncthing
  stack: syncthing
  ################################
  # IMAGE/PROCESS
  ################################
  image: lscr.io/linuxserver/syncthing:v2.1.3-ls227
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_storage_host].container_host_puid }}"
    PGID: "{{ hostvars[services_storage_host].container_host_pgid }}"
    UMASK: "022"
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ports:
    listening_tcp:
      published: 22000
      target: 22000
      mode: host
    listening_udp:
      published: 22000
      target: 22000
      protocol: udp
      mode: host
    discovery:
      published: 21027
      target: 21027
      protocol: udp
      mode: host
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/syncthing"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/syncthing"
      target: /config
      read_only: false
    media:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_data_root }}"
      target: /data
      read_only: false
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 8384
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_storage_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
