---

syncthing:
  name: syncthing
  stack: syncthing
  image: lscr.io/linuxserver/syncthing:v2.1.0-ls218
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[docker_services_unraid_host].docker_host_puid }}"
    PGID: "{{ hostvars[docker_services_unraid_host].docker_host_pgid }}"
    UMASK: "022"
  ports:
    listening_tcp:
      published: 22000
      target: 22000
      mode: host
    listening_udp:
      published: 22000
      target: 22000
      protocol: udp
      mode: host
    discovery:
      published: 21027
      target: 21027
      protocol: udp
      mode: host
  paths:
    - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/syncthing"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/syncthing"
      target: /config
      read_only: false
    media:
      type: bind
      source: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}"
      target: /data
      read_only: false
  traefik:
    enable: true
    exposure: private
    port: 8384
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_unraid_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
