---

tautulli:
  enabled: true
  tags: [apps, plex, tautulli]
  name: tautulli
  stack: tautulli
  image: ghcr.io/hotio/tautulli:release-v2.17.2
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[docker_services_plex_host].docker_host_puid }}"
    PGID: "{{ hostvars[docker_services_plex_host].docker_host_pgid }}"
    UMASK: "022"
    WEBUI_PORTS: "8181/tcp,8181/udp"
    TP_SCHEME: "http"
    TP_DOMAIN: "{{ hostvars[docker_services_primary_manager].local_ip }}:8089"
    TP_HOTIO: "true"
    TP_THEME: "hotline"
  paths:
    - path: "{{ hostvars[docker_services_plex_host].docker_host_appdata_root }}/tautulli"
      state: directory
      mode: "0755"
  copies:
    - src: files/themepark/98-themepark-tautulli
      dest: "{{ hostvars[docker_services_plex_host].docker_host_appdata_root }}/tautulli/98-themepark-tautulli"
      mode: "0755"
      force: false
      wait: true
      wait_timeout: 30
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_plex_host].docker_host_appdata_root }}/tautulli"
      target: /config
      read_only: false
    themepark:
      type: bind
      source: "{{ hostvars[docker_services_plex_host].docker_host_appdata_root }}/tautulli/98-themepark-tautulli"
      target: /etc/cont-init.d/98-themepark
      read_only: false
  traefik:
    enable: true
    exposure: private
    port: 8181
  themepark:
    app: tautulli
    theme: hotpink
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_plex_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_plex_host
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
