---

tautulli:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: docker
  tags: [plex, tautulli]
  name: tautulli
  stack: tautulli
  ################################
  # IMAGE/PROCESS
  ################################
  image: ghcr.io/hotio/tautulli:release-v2.17.2
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_plex_host].container_host_puid }}"
    PGID: "{{ hostvars[services_plex_host].container_host_pgid }}"
    UMASK: "022"
    WEBUI_PORTS: "8181/tcp,8181/udp"
    TP_SCHEME: "http"
    TP_DOMAIN: "{{ hostvars[services_controller_host].local_ip }}:8089"
    TP_HOTIO: "true"
    TP_THEME: "hotline"
  infisical:
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_plex_host].container_host_appdata_root }}/tautulli"
      state: directory
      mode: "0755"
  copies:
    - src: files/themepark/98-themepark-tautulli
      dest: "{{ hostvars[services_plex_host].container_host_appdata_root }}/tautulli/98-themepark-tautulli"
      mode: "0755"
      force: false
      wait: true
      wait_timeout: 30
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_plex_host].container_host_appdata_root }}/tautulli"
      target: /config
      read_only: false
    themepark:
      type: bind
      source: "{{ hostvars[services_plex_host].container_host_appdata_root }}/tautulli/98-themepark-tautulli"
      target: /etc/cont-init.d/98-themepark
      read_only: false
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 8181
  themepark:
    app: tautulli
    theme: hotpink
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_plex_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_plex_host
