---

technitium:
  enabled: true
  tags: [dns]
  image: technitium/dns-server:15.3.0
  named_networks:
    outside:
      external: true
      name: host
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: technitium_admin_pass
        path: "/Technitium"
        name: ADMIN_PASS
        docker_secret: technitium_admin_secret
  secrets:
    - technitium_admin_secret
  environment:
    TZ: "{{ timezone }}"
    UMASK: "022"
    DNS_SERVER_ADMIN_PASSWORD_FILE: /run/secrets/technitium_admin_secret
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: careful
  targets:
    ################################
    # TECHNITIUM PRIMARY SERVICE
    ################################
    technitium_primary:
      name: technitium-primary
      stack: technitium-primary
      tags: [technitium-primary, dns-primary]
      environment:
        PUID: "{{ hostvars[docker_services_primary_manager].docker_host_puid }}"
        PGID: "{{ hostvars[docker_services_primary_manager].docker_host_pgid }}"
      paths:
        - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/technitium"
          state: directory
          mode: "0755"
      volumes:
        config:
          type: bind
          source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/technitium"
          target: /etc/dns
          read_only: false
      deploy:
        host: "{{ docker_services_primary_manager }}"
        constraints:
          - "node.hostname == {{ docker_services_primary_manager }}"

    ################################
    # TECHNITIUM SECONDARY SERVICE
    ################################
    technitium_secondary:
      name: technitium-secondary
      stack: technitium-secondary
      tags: [technitium-secondary, dns-secondary]
      environment:
        PUID: "{{ hostvars[docker_services_plex_host].docker_host_puid }}"
        PGID: "{{ hostvars[docker_services_plex_host].docker_host_pgid }}"
      paths:
        - path: "{{ hostvars[docker_services_plex_host].docker_host_appdata_root }}/technitium"
          state: directory
          mode: "0755"
      volumes:
        config:
          type: bind
          source: "{{ hostvars[docker_services_plex_host].docker_host_appdata_root }}/technitium"
          target: /etc/dns
          read_only: false
      deploy:
        host: "{{ docker_services_plex_host }}"
        constraints:
          - "node.hostname == {{ docker_services_plex_host }}"
