---

thelounge:
  ################################
  # IDENTITY
  ################################
  enabled: true
  runtime: podman
  tags: [media, thelounge]
  name: thelounge
  ################################
  # IMAGE/PROCESS
  ################################
  image: lscr.io/linuxserver/thelounge:v4.5.2-ls229
  user: "0:0"
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_controller_host].container_host_puid }}"
    PGID: "{{ hostvars[services_controller_host].container_host_pgid }}"
    UMASK: "022"
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    thelounge:
      driver: bridge
      external: false
  ports:
    - host_ip: "{{ local_ip }}"
      published: 19000
      target: 9000
      protocol: tcp
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/thelounge"
      state: directory
      mode: "0750"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/thelounge"
      target: /config
      read_only: false
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 19000
    backend_mode: host
    backend_host_inventory: "{{ services_controller_host }}"
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: container
    host: "{{ services_controller_host }}"
    execution:
      mode: rootless
      host_user: podman-thelounge
      userns:
        mode: keep-id
        uid: "{{ hostvars[services_controller_host].container_host_puid }}"
        gid: "{{ hostvars[services_controller_host].container_host_pgid }}"
  systemd:
    after: [network-online.target]
    restart: on-failure
    restart_sec: 10s
    timeout_start_sec: 900s
