---

themepark:
  enabled: true
  tags: [utilities, themepark]
  name: theme-park
  stack: themepark
  image: ghcr.io/themepark-dev/theme.park:1.22.0
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[docker_services_primary_manager].docker_host_puid }}"
    PGID: "{{ hostvars[docker_services_primary_manager].docker_host_pgid }}"
    UMASK: "022"
  ports:
    web:
      published: 8089
      target: 80
      mode: host
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/theme-park"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/theme-park"
      target: /config
      read_only: false
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
