---

traefik:
  enabled: true
  runtime: docker
  tags: [proxy, traefik]
  name: traefik
  stack: traefik

  image: traefik:v3.7.8

  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_controller_host].container_host_puid }}"
    PGID: "{{ hostvars[services_controller_host].container_host_pgid }}"
    UMASK: "022"
    CF_DNS_API_TOKEN_FILE: /run/secrets/cloudflare_api_secret
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: cloudflare_api
        path: "/Cloudflare"
        name: API
        secret:
          name: cloudflare_api_secret
      - var: cloudflare_zone
        path: "/Cloudflare"
        name: ZONE
      - var: crowdsec_traefik_bouncer_key
        path: "/CrowdSec"
        name: TRAEFIK_BOUNCER_KEY
        secret:
          name: crowdsec_traefik_bouncer_key_secret

  named_networks:
    overlay:
      external: true
  ports:
    web:
      published: 80
      target: 80
      mode: host
    web_secure:
      published: 443
      target: 443
      mode: host
    web_secure_private:
      published: 8443
      target: 8443
      mode: host

  paths:
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/traefik"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/traefik/dynamic"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_controller_host].container_host_appdata_root }}/traefik/acme.json"
      state: touch
      mode: "0600"
    - path: "{{ services_log_root }}"
      state: directory
      owner: "0"
      group: "0"
      mode: "0755"
    - path: "{{ services_log_root }}/traefik"
      state: directory
      owner: "0"
      group: "0"
      mode: "0755"
  templates:
    - src: configs/proxy/traefik/config.yml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/traefik/traefik.yml"
      mode: "0664"
      force: true
      no_log: true
    - src: configs/proxy/traefik/middlewares.yml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/traefik/dynamic/middlewares.yml"
      mode: "0664"
      force: true
    - src: configs/proxy/authelia/middleware.yml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/traefik/dynamic/authelia-middleware.yml"
      mode: "0664"
    - src: configs/proxy/authelia/router.yml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/traefik/dynamic/authelia-router.yml"
      mode: "0664"
      force: true
      no_log: true
    - src: configs/proxy/traefik/dashboard.yml.j2
      dest: "{{ hostvars[services_controller_host].container_host_appdata_root }}/traefik/dynamic/traefik-dashboard.yml"
      mode: "0664"
      force: true
      no_log: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_controller_host].container_host_appdata_root }}/traefik"
      target: /etc/traefik
      read_only: false
    logs:
      type: bind
      source: "{{ services_log_root }}/traefik"
      target: /etc/traefik/logs
      read_only: false

  healthcheck:
    test:
      - "CMD"
      - "wget"
      - "--spider"
      - "-q"
      - "http://127.0.0.1:8081/ping"

  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: careful
    host: "{{ services_controller_host }}"
    constraints:
      - node.labels.docker_services_host == services_controller_host
