---

traefik:
  name: traefik
  stack: traefik
  image: traefik:v3.6.14
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD"
      - "wget"
      - "--spider"
      - "-q"
      - "http://127.0.0.1:8081/ping"
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[docker_services_primary_manager].docker_host_puid }}"
    PGID: "{{ hostvars[docker_services_primary_manager].docker_host_pgid }}"
    UMASK: "022"
    CF_DNS_API_TOKEN_FILE: /run/secrets/cloudflare_api_secret
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: cloudflare_api
        path: "/Cloudflare"
        name: API
        docker_secret: cloudflare_api_secret
  secrets:
    - cloudflare_api_secret
  ports:
    web:
      published: 80
      target: 80
      mode: host
    web_secure:
      published: 443
      target: 443
      mode: host
    web_secure_private:
      published: 8443
      target: 8443
      mode: host
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/traefik"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/traefik/dynamic"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/traefik/acme.json"
      state: touch
      mode: "0600"
  templates:
    - src: configs/proxy/traefik/config.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/traefik/traefik.yml"
      mode: "0664"
      force: true
    - src: configs/proxy/traefik/middlewares.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/traefik/dynamic/middlewares.yml"
      mode: "0664"
      force: true
    - src: configs/proxy/authelia/middleware.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/traefik/dynamic/authelia-middleware.yml"
      mode: "0664"
    - src: configs/proxy/authelia/router.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/traefik/dynamic/authelia-router.yml"
      mode: "0664"
      force: true
    - src: configs/proxy/traefik/dashboard.yml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/traefik/dynamic/traefik-dashboard.yml"
      mode: "0664"
      force: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/traefik"
      target: /etc/traefik
      read_only: false
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
