---

whisparr:
################################
# IDENTITY
################################
  enabled: true
  runtime: docker
  tags: [arrs, pgsql, whisparr]
  name: whisparr
  stack: whisparr
  ################################
  # IMAGE/PROCESS
  ################################
  image: ghcr.io/hotio/whisparr:v3-3.3.4-release.794
  ################################
  # ENVIRONMENT/SECRETS
  ################################
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[services_storage_host].container_host_puid }}"
    PGID: "{{ hostvars[services_storage_host].container_host_pgid }}"
    UMASK: "022"
    WHISPARR__APP__INSTANCENAME: "Whisparr"
    WHISPARR__SERVER__PORT: "6969"
    WHISPARR__AUTH__METHOD: "External"
    FILE__WHISPARR__AUTH__APIKEY: /run/secrets/whisparr_api_secret
    WHISPARR__POSTGRES__HOST: "haproxy"
    WHISPARR__POSTGRES__PORT: "5432"
    FILE__WHISPARR__POSTGRES__USER: /run/secrets/postgres_user_secret
    FILE__WHISPARR__POSTGRES__PASSWORD: /run/secrets/postgres_pass_secret
    WHISPARR__POSTGRES__MAINDB: "whisparr-main-v3"
    WHISPARR__POSTGRES__LOGDB: "whisparr-log-v3"
    TP_SCHEME: "http"
    TP_DOMAIN: "{{ hostvars[services_controller_host].local_ip }}:8089"
    TP_HOTIO: "true"
    TP_THEME: "hotline"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: cloudflare_zone
        path: /Cloudflare
        name: ZONE
      - var: whisparr_api
        path: "/Whisparr"
        name: API
        secret:
          name: whisparr_api_secret
      - var: postgres_user
        path: "/Postgres"
        name: USER
        secret:
          name: postgres_user_secret
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
        secret:
          name: postgres_pass_secret
  ################################
  # CONNECTIVITY
  ################################
  named_networks:
    overlay:
      external: true
  ################################
  # FILESYSTEM
  ################################
  paths:
    - path: "{{ hostvars[services_storage_host].container_host_appdata_root }}/whisparr"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[services_storage_host].container_host_data_root }}/media/adult"
      state: directory
      mode: "0755"
  copies:
    - src: files/themepark/98-themepark-whisparr
      dest: "{{ hostvars[services_storage_host].container_host_appdata_root }}/whisparr/98-themepark-whisparr"
      mode: "0755"
      force: false
      wait: true
      wait_timeout: 30
  volumes:
    config:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/whisparr"
      target: /config
      read_only: false
    media:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_data_root }}"
      target: /data
      read_only: false
    themepark:
      type: bind
      source: "{{ hostvars[services_storage_host].container_host_appdata_root }}/whisparr/98-themepark-whisparr"
      target: /etc/cont-init.d/98-themepark
      read_only: false
  ################################
  # HEALTH
  ################################
  healthcheck:
    test:
      - "CMD-SHELL"
      - "touch /data/media/adult/.healthcheck && rm -f /data/media/adult/.healthcheck || exit 1"
  ################################
  # INTEGRATIONS
  ################################
  traefik:
    enable: true
    exposure: private
    port: 6969
  themepark:
    app: whisparr
    theme: hotline
  postgres:
    enable: true
    databases:
      - whisparr-main-v3
      - whisparr-log-v3
  ################################
  # RUNTIME/LIFECYCLE
  ################################
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    profile: standard
    host: "{{ services_storage_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
