---

znc:
  name: znc
  stack: znc
  image: lscr.io/linuxserver/znc:znc-1.10.1-ls179
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[docker_services_primary_manager].docker_host_puid }}"
    PGID: "{{ hostvars[docker_services_primary_manager].docker_host_pgid }}"
    UMASK: "022"
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/znc"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/znc"
      target: /config
      read_only: false
  traefik:
    enable: true
    exposure: private
    port: 6501
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
