---

docker_services_primary_manager: mgt
docker_services_plex_host: plex
docker_services_unraid_host: unraid

docker_services:
  ## services (core)
  - name: gitea
    tags: [apps, gitea]
  - name: homepage
    tags: [apps, homepage]
  - name: portainer
    target: agent
    tags: [apps, portainer]
  - name: portainer
    target: main
    tags: [apps, portainer]
  - name: technitium
    tags: [apps, technitium]
  - name: vaultwarden
    tags: [apps, vaultwarden]

  ## services (proxy)
  - name: authelia
    target: redis
    tags: [apps, proxy, authelia]
  - name: authelia
    target: main
    tags: [apps, proxy, authelia]
  - name: traefik
    tags: [apps, proxy, traefik]

  ## services (arrs)
  - name: bazarr
    tags: [apps, arrs, bazarr]
  - name: lidarr
    tags: [apps, arrs, lidarr]
  - name: prowlarr
    tags: [apps, arrs, prowlarr]
  - name: radarr
    target: radarr
    tags: [apps, arrs, radarr]
  - name: radarr
    target: radarr_4k
    tags: [apps, arrs, radarr]
  - name: recyclarr
    tags: [apps, arrs, recyclarr]
  - name: sonarr
    target: sonarr
    tags: [apps, arrs, sonarr]
  - name: sonarr
    target: sonarr_4k
    tags: [apps, arrs, sonarr]
  - name: sportarr
    tags: [apps, arrs, sportarr]
  - name: whisparr
    tags: [apps, arrs, whisparr]

  ## services (media)
  - name: autobrr
    tags: [apps, media, autobrr]
  - name: seerr
    tags: [apps, media, seerr]
  - name: ombi
    tags: [apps, media, ombi]
  - name: opencloud
    tags: [apps, opencloud]
  - name: stash
    tags: [apps, media, stash]
  - name: thelounge
    tags: [apps, media, thelounge]
  - name: znc
    tags: [apps, media, znc]

  ## services (plex)
  - name: autopulse
    target: user_interface
    tags: [apps, plex, autopulse]
  - name: autopulse
    target: main
    tags: [apps, plex, autopulse]
  - name: imagemaid
    tags: [apps, plex, imagemaid]
  - name: kometa
    tags: [apps, plex, kometa]
  - name: plex
    tags: [apps, plex, plex_server]
  - name: tautulli
    tags: [apps, plex, tautulli]

  ## services (torrents)
  - name: qbittorrent
    target: downloads
    tags: [torrents, qbittorrent]
  - name: qbittorrent
    target: seeds
    tags: [torrents, qbittorrent]
  - name: qbit_manage
    target: downloads
    tags: [torrents, qbit_manage]
  - name: qbit_manage
    target: seeds
    tags: [torrents, qbit_manage]
  - name: qui
    tags: [torrents, qui]
  - name: unpackerr
    tags: [torrents, unpackerr]

  ## services (usenet)
  - name: nzbhydra2
    tags: [apps, usenet, nzbhydra2]
  - name: sabnzbd
    tags: [apps, usenet, sabnzbd]

  ## services (monitoring)
  - name: alloy
    tags: [apps, monitoring, alloy]
  - name: gotify
    tags: [apps, monitoring, gotify]
  - name: grafana
    tags: [apps, monitoring, grafana]
  - name: loki
    tags: [apps, monitoring, loki]
  - name: prometheus
    tags: [apps, monitoring, prometheus]
  - name: scraparr
    tags: [apps, monitoring, scraparr]

  ## services (blog)
  - name: obsidian
    tags: [apps, blog, obsidian]

  ## services (gluetun)
  - name: gluetun
    tags: [apps, gluetun]
  - name: jdownloader2
    tags: [apps, gluetun, jdownloader2]
  - name: librewolf
    tags: [apps, gluetun, librewolf]

  ## services (utilities)
  - name: adminer
    tags: [apps, utilities, adminer]
  - name: czkawka
    tags: [apps, utilities, czkawka]
  - name: themepark
    tags: [apps, utilities, themepark]

  ## services (postgres cluster)
  - name: etcd
    target: pg01
    tags: [etcd, pg01]
  - name: etcd
    target: pg02
    tags: [etcd, pg02]
  - name: etcd
    target: pg03
    tags: [etcd, pg03]
  - name: spilo
    target: pg01
    tags: [spilo, pg01]
  - name: spilo
    target: pg02
    tags: [spilo, pg02]
  - name: spilo
    target: pg03
    tags: [spilo, pg03]
  - name: haproxy
    tags: [haproxy]

  ## services (unifi)
  - name: unifi
    tags: [apps, unifi]
