---

docker_swarm_primary_manager: mgt
docker_swarm_hostname: "{{ inventory_hostname }}"
docker_network: overlay

docker_services_primary_manager: mgt
docker_services_plex_host: plex
docker_services_unraid_host: unraid
docker_services_log_root: /var/log/skynet

docker_services_drift_email_enabled: true
docker_services_drift_email_infisical_path: /Porkbun
docker_services_drift_email_secure: starttls
docker_services_drift_email_subject: "Skynet Docker image drift detected"
