---

docker_services_primary_manager: mgt
docker_services_plex_host: plex
docker_services_unraid_host: unraid

docker_services:
  ## services (arrs)
  - name: bazarr
    tags: [apps, arrs, pgsql, bazarr]
  - name: lidarr
    tags: [apps, arrs, pgsql, lidarr]
  - name: prowlarr
    tags: [apps, arrs, pgsql, prowlarr]
  - name: radarr
    target: radarr
    tags: [apps, arrs, pgsql, radarr]
  - name: radarr
    target: radarr_4k
    tags: [apps, arrs, pgsql, radarr]
  - name: recyclarr
    tags: [apps, arrs, recyclarr]
  - name: sonarr
    target: sonarr
    tags: [apps, arrs, pgsql, sonarr]
  - name: sonarr
    target: sonarr_4k
    tags: [apps, arrs, pgsql, sonarr]
  - name: sportarr
    tags: [apps, arrs, sportarr]
  - name: whisparr
    tags: [apps, arrs, pgsql, whisparr]

  ## services (gluetun)
  - name: gluetun
    tags: [apps, gluetun]
  - name: jdownloader2
    tags: [apps, gluetun, jdownloader2]
  - name: librewolf
    tags: [apps, gluetun, librewolf]

  ## services (media)
  - name: autobrr
    tags: [apps, media, pgsql, autobrr]
  - name: seerr
    tags: [apps, media, pgsql, seerr]
  - name: obsidian
    tags: [apps, media, obsidian]
  - name: ombi
    tags: [apps, media, pgsql, ombi]
  - name: opencloud
    tags: [apps, opencloud]
  - name: stash
    tags: [apps, media, pgsql, stash]
  - name: thelounge
    tags: [apps, media, thelounge]
  - name: znc
    tags: [apps, media, znc]

  ## services (monitoring)
  - name: alloy
    tags: [apps, monitoring, alloy]
  - name: crowdsec
    tags: [apps, monitoring, crowdsec]
  - name: gotify
    tags: [apps, monitoring, pgsql, gotify]
  - name: grafana
    tags: [apps, monitoring, grafana]
  - name: homepage
    tags: [apps, monitoring, homepage]
  - name: loki
    tags: [apps, monitoring, loki]
  - name: portainer
    target: agent
    tags: [apps, monitoring, portainer]
  - name: portainer
    target: main
    tags: [apps, monitoring, portainer]
  - name: prometheus
    tags: [apps, monitoring, prometheus]
  - name: scraparr
    tags: [apps, monitoring, scraparr]
  - name: uptime_kuma
    tags: [apps, monitoring, uptime_kuma]

  ## services (network)
  - name: authelia
    target: redis
    tags: [apps, network, proxy, pgsql, authelia]
  - name: authelia
    target: main
    tags: [apps, network, proxy, pgsql, authelia]
  - name: haproxy
    tags: [apps, network, haproxy]
  - name: netbox
    target: main
    tags: [apps, network, pgsql, netbox]
  - name: netbox
    ## If first deploy, the worker may fail, wait for main instance to be healthy and then re-run the role
    target: worker
    tags: [apps, network, pgsql, netbox]
  - name: netbox
    target: redis
    tags: [apps, network, pgsql, netbox]
  - name: netbox
    target: redis_cache
    tags: [apps, network, pgsql, netbox]
  - name: technitium
    tags: [apps, network, technitium]
  - name: traefik
    tags: [apps, network, proxy, traefik]
  - name: unifi
    tags: [apps, network, unifi]

  ## services (plex)
  - name: autopulse
    target: user_interface
    tags: [apps, plex, pgsql, autopulse]
  - name: autopulse
    target: main
    tags: [apps, plex, pgsql, autopulse]
  - name: imagemaid
    tags: [apps, plex, imagemaid]
  - name: kometa
    tags: [apps, plex, kometa]
  - name: plex
    tags: [apps, plex, plex_server]
  - name: tautulli
    tags: [apps, plex, tautulli]

  ## services (torrents)
  - name: qbittorrent
    target: downloads
    tags: [apps, torrents, qbittorrent]
  - name: qbittorrent
    target: seeds
    tags: [apps, torrents, qbittorrent]
  - name: qui
    tags: [apps, torrents, pgsql, qui]
  - name: unpackerr
    tags: [apps, torrents, unpackerr]

  ## services (usenet)
  - name: nzbhydra2
    tags: [apps, usenet, nzbhydra2]
  - name: sabnzbd
    tags: [apps, usenet, sabnzbd]

  ## services (utilities)
  - name: adminer
    tags: [apps, utilities, adminer]
  - name: czkawka
    tags: [apps, utilities, czkawka]
  - name: gitea
    tags: [apps, utilities, pgsql, gitea]
  - name: themepark
    tags: [apps, utilities, themepark]
  - name: vaultwarden
    tags: [apps, utilities, pgsql, vaultwarden]
