---

# Required sensitive variables are defined in:
# ansible/group_vars/all/vault.yml
#
# For the expected structure, see:
# ansible/group_vars/all/vault.yml.sample

################################
# INFISICAL (COLLECTION)
################################

infisical_lookup_default_params:
  auth_method: "universal_auth"
  universal_auth_client_id: "{{ infisical_auth_client_id }}"
  universal_auth_client_secret: "{{ infisical_auth_client_secret }}"
  project_id: "{{ infisical_project_id }}"
  env_slug: "prod"
  url: "http://{{ local_ip }}:8066"
