---

quiet: true
compact: true

skip-path:
  - "^ansible/collections/"
  - "^ansible/.*/files/"
  - "^ansible/.*/templates/"
  - "^ansible/docs/"
  - "^ansible/roles/docker_services/README.md"
  - "^\\.ansible/"
  - "^.*/__pycache__/"
