---

terraform_prereq_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common

terraform_opentofu_source_url: "https://packages.opentofu.org/opentofu/tofu/any/"
terraform_opentofu_source_suite: any
terraform_keyring_dir: /etc/apt/keyrings
terraform_keyring_file_opentofu: /etc/apt/keyrings/opentofu.gpg
terraform_keyring_file_repo: /etc/apt/keyrings/opentofu-repo.gpg
terraform_repo_filename: opentofu

terraform_packages:
  - tofu
