---

pgha_etcd_cluster_token: pg-ha-1
pgha_etcd_data_dir: /var/lib/etcd
pgha_etcd_config_dir: /etc/etcd
pgha_etcd_config_path: "{{ pgha_etcd_config_dir }}/etcd.conf.yml"

pgha_etcd_client_port: 2379
pgha_etcd_peer_port: 2380

pgha_patroni_scope: pg-cluster
pgha_patroni_namespace: /service

pgha_patroni_restapi_port: 8008
pgha_patroni_postgres_port: 5433

pgha_patroni_data_dir: /var/lib/postgresql/18/main
pgha_patroni_bin_dir: /usr/lib/postgresql/18/bin
pgha_patroni_config_dir: /etc/patroni
pgha_patroni_config_path: "{{ pgha_patroni_config_dir }}/patroni.yml"

pgha_patroni_superuser_name: postgres
pgha_patroni_replication_name: replicator

pgha_patroni_postgresql_parameters:
  max_connections: 100
  shared_buffers: 1GB
  wal_level: replica
  hot_standby: "on"
  max_wal_senders: 10
  max_replication_slots: 10
  wal_keep_size: 1GB
  max_worker_processes: 8
  max_locks_per_transaction: 64
  max_prepared_transactions: 0
  track_commit_timestamp: "off"
  password_encryption: scram-sha-256

pgha_patroni_admin_role_login: true
pgha_patroni_admin_role_createdb: true
pgha_patroni_admin_role_createrole: false
