---

- name: Ensure docker_services_service_name is set
  ansible.builtin.assert:
    that:
      - docker_services_service_name is defined
      - docker_services_service_name | trim | length > 0
    fail_msg: "docker_services_service_name must be set before calling this helper"

- name: Set SHM size for service
  ansible.builtin.set_fact:
    docker_services_compose_services: >-
      {{
        (docker_services_compose_services | default({}))
        | combine({
            docker_services_service_name: (
              ((docker_services_compose_services | default({})).get(docker_services_service_name, {}))
              | combine({
                  'shm_size': shm_size
                }, recursive=true)
            )
          }, recursive=true)
      }}
