---

################################
# QBITORRENT PREP
################################

- name: qBittorrent prep | Set qBittorrent hosts
  ansible.builtin.set_fact:
    docker_services_qbittorrent_host: "plex"
    docker_services_qbittorrent_xs_host: "plex"
  run_once: true

################################
# HASH PASSWORD
################################

- name: qBittorrent prep | Generate pass
  when: (docker_services_svc.name | default('') | string | trim) == "qbittorrent"
  qbittorrent_passwd:
    password: '{{ qbittorrent_pass }}'
  register: docker_services_qbittorrent_pass_pbkdf2
  delegate_to: "{{ docker_services_qbittorrent_host }}"
  run_once: true

- name: qBittorrent prep | Generate xs-instance pass
  when: (docker_services_svc.name | default('') | string | trim) == "qbittorrent-xs"
  qbittorrent_passwd:
    password: '{{ qbittorrent_xs_pass }}'
  register: docker_services_qbittorrent_xs_pass_pbkdf2
  delegate_to: "{{ docker_services_qbittorrent_xs_host }}"
  run_once: true
