---

docker_manage_user: true
docker_user: "mgt"

docker_swarm_node_labels:
  role: manager
  ansible_host: mgt
  docker_services_host: docker_services_primary_manager
  haproxy: "true"
  dns: technitium

podman_install_enable: true
