---

puid: 99
pgid: 100

local_ip: 192.168.80.20

docker_swarm_hostname: "unraid"

docker_host_puid: 99
docker_host_pgid: 100
docker_host_appdata_root: /mnt/user/appdata
docker_host_data_root: /mnt/user/data

docker_host_opencloud_puid: 1000
docker_host_opencloud_pgid: 1000
docker_host_opencloud_data_root: /mnt/user/opencloud/data

docker_swarm_node_labels:
  role: worker
  ansible_host: unraid
  docker_services_host: docker_services_unraid_host
  haproxy: "true"
