---

- name: Ubuntu | Install common packages
  when: ubuntu_apt_enabled | default(true) | bool
  ansible.builtin.include_tasks:
    file: sub_tasks/apt.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_apt
  tags:
    - ubuntu
    - ubuntu_apt

- name: Ubuntu | Install PostgreSQL backup prerequisites
  when:
    - "'tags_postgres' in group_names"
    - ubuntu_apt_enabled | default(true) | bool
  ansible.builtin.include_tasks:
    file: sub_tasks/postgres_backup_prerequisites.yml
    apply:
      tags:
        - never
        - postgres_backup
        - postgres_backup_setup
        - postgres_backup_run
  tags:
    - never
    - postgres_backup
    - postgres_backup_setup
    - postgres_backup_run

- name: Ubuntu | Clone Homelab repo
  when: "'tags_ansible_manager' in group_names"
  ansible.builtin.include_tasks:
    file: sub_tasks/repo.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_repo
  tags:
    - ubuntu
    - ubuntu_repo

- name: Ubuntu | Setup Python venv
  when: "'tags_ansible_manager' in group_names"
  ansible.builtin.include_tasks:
    file: sub_tasks/venv.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_venv
  tags:
    - ubuntu
    - ubuntu_venv

- name: Ubuntu | Install required collections
  when: "'tags_ansible_manager' in group_names"
  ansible.builtin.include_tasks:
    file: sub_tasks/requirements.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_requirements
  tags:
    - ubuntu
    - ubuntu_requirements

- name: Ubuntu | Install Skynet wrapper
  when: "'tags_ansible_manager' in group_names"
  ansible.builtin.include_tasks:
    file: sub_tasks/skynet.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_skynet
  tags:
    - ubuntu
    - ubuntu_skynet

- name: Ubuntu | Tune sysctl settings
  when: ubuntu_sysctl_enabled | default(true) | bool
  ansible.builtin.include_tasks:
    file: sub_tasks/sysctl.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_sysctl
  tags:
    - ubuntu
    - ubuntu_sysctl

- name: Ubuntu | Set PAM limits
  ansible.builtin.include_tasks:
    file: sub_tasks/pam.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_pam
  tags:
    - ubuntu
    - ubuntu_pam

- name: Ubuntu | Configure network tuning
  ansible.builtin.include_tasks:
    file: sub_tasks/network.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_network
  tags:
    - ubuntu
    - ubuntu_network

- name: Ubuntu | Configure Netplan
  when:
    - ubuntu_netplan_enabled | bool
    - (ansible_facts.virtualization_type | default("")) != "lxc"
  ansible.builtin.include_tasks:
    file: sub_tasks/netplan.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_netplan
  tags:
    - ubuntu
    - ubuntu_netplan
