---

- name: Install common apt packages
  ansible.builtin.include_tasks:
    file: sub_tasks/apt.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_apt
  tags:
    - ubuntu
    - ubuntu_apt

- name: Clone Homelab repo
  when: inventory_hostname in groups['ansible_managers']
  ansible.builtin.include_tasks:
    file: sub_tasks/repo.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_repo
  tags:
    - ubuntu
    - ubuntu_repo

- name: Setup Python venv
  when: inventory_hostname in groups['ansible_managers']
  ansible.builtin.include_tasks:
    file: sub_tasks/venv.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_venv
  tags:
    - ubuntu
    - ubuntu_venv

- name: Install required collections and pip packages
  when: inventory_hostname in groups['ansible_managers']
  ansible.builtin.include_tasks:
    file: sub_tasks/requirements.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_requirements
  tags:
    - ubuntu
    - ubuntu_requirements

- name: Install Skynet wrapper
  when: inventory_hostname in groups['ansible_managers']
  ansible.builtin.include_tasks:
    file: sub_tasks/skynet.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_skynet
  tags:
    - ubuntu
    - ubuntu_skynet

- name: Tune sysctl settings
  ansible.builtin.include_tasks:
    file: sub_tasks/sysctl.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_sysctl
  tags:
    - ubuntu
    - ubuntu_sysctl

- name: Set PAM limits
  ansible.builtin.include_tasks:
    file: sub_tasks/pam.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_pam
  tags:
    - ubuntu
    - ubuntu_pam

- name: Configure network tuning
  ansible.builtin.include_tasks:
    file: sub_tasks/network.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_network
  tags:
    - ubuntu
    - ubuntu_network

- name: Configure Netplan
  when: inventory_hostname not in (groups['opentofu_managed'] | default([]))
  ansible.builtin.include_tasks:
    file: sub_tasks/netplan.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_netplan
  tags:
    - ubuntu
    - ubuntu_netplan
