---

################################
# COMPOSE (LABELS)
################################

- name: Attach labels (service-level)
  when:
    - docker_services_is_deploy_host
    - docker_services_svc.labels is defined
    - (docker_services_svc.labels is mapping) or (docker_services_svc.labels is sequence and docker_services_svc.labels is not string)
    - (docker_services_svc.labels | length > 0)
  ansible.builtin.include_tasks: _labels.yml
  vars:
    labels_dict: "{{ docker_services_svc.labels }}"
    labels_action: "append"
    labels_precedence: "new_wins"
