---

################################
# INIT
################################

- name: Init (validate + normalize)
  ansible.builtin.include_tasks:
    file: _init.yml
    apply:
      tags: [deploy, update, remove, recreate, bootstrap]
  tags: [deploy, update, remove, recreate, bootstrap]

################################
# PREP
################################

- name: Prep | cleanup tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/prep/_00_cleanup.yml"
  tags: [remove, recreate]

- name: Prep | Pre-template tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/prep/_01_pre_template.yml"
  tags: [deploy, update, recreate, bootstrap]

- name: Prep | filesystem tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/prep/_02_filesystem.yml"
  tags: [deploy, update, recreate]

- name: Prep | Relevant services tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/prep/_03_misc_service_prep.yml"
  tags: [deploy, update, recreate, bootstrap]

################################
# COMPOSE
################################

- name: Compose | Init tasks
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/compose/_00_init.yml"
    apply:
      tags: [deploy, update, recreate]
  tags: [deploy, update, recreate]

- name: Compose | Service Base tasks
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/prep/_01_base.yml"
    apply:
      tags: [deploy, update, recreate]
  tags: [deploy, update, recreate]

- name: Compose | Runtime tasks
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/prep/_02_runtime.yml"
    apply:
      tags: [deploy, update, recreate]
  tags: [deploy, update, recreate]

- name: Compose | Input-Output tasks
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/prep/_03_io.yml"
    apply:
      tags: [deploy, update, recreate]
  tags: [deploy, update, recreate]

- name: Compose | Metadata tasks
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/prep/_04_metadata.yml"
    apply:
      tags: [deploy, update, recreate]
  tags: [deploy, update, recreate]

################################
# DEPLOY
################################

- name: Run centralized deploy (once)
  ansible.builtin.include_tasks:
    file: _deploy.yml
    apply:
      tags: [deploy, update, recreate]
  tags: [deploy, update, recreate]
