---

################################
# GLOBAL / CENTRAL STATE INIT
################################

- name: Ensure docker_services_compose_stacks exists on mgt
  ansible.builtin.set_fact:
    docker_services_compose_stacks: "{{ docker_services_compose_stacks | default({}) }}"
  delegate_to: "{{ docker_services_primary_manager | default('mgt') }}"
  delegate_facts: true
  run_once: true

- name: Load this stack's current docker_services_compose_services
  when: docker_services_is_deploy_host
  ansible.builtin.set_fact:
    docker_services_compose_services: >-
      {{
        (docker_services_compose_stacks | default({}))
        .get(docker_services_stack_name_effective, {})
        .get('services', {})
        | default({}, true)
      }}
