---

################################
# DEPLOY (QUEUE STACK)
################################

- name: Set deploy config (swarm only, compose structure)
  when:
    - docker_services_is_deploy_host
    - (docker_services_svc.deploy is defined)
    - ((docker_services_svc.deploy.type | default('swarm')) == 'swarm')
  ansible.builtin.include_tasks: _deploy_config.yml
  vars:
    deploy_mode: "{{ docker_services_svc.deploy.mode | default('replicated') }}"
    deploy_replicas: "{{ docker_services_svc.deploy.replicas | default(1) }}"
    deploy_constraints: "{{ docker_services_svc.deploy.constraints | default([]) }}"
    deploy_restart_policy: "{{ docker_services_svc.deploy.restart_policy | default(omit) }}"
    deploy_update_config: "{{ docker_services_svc.deploy.update_config | default(omit) }}"
    deploy_rollback_config: "{{ docker_services_svc.deploy.rollback_config | default(omit) }}"
    deploy_resources: "{{ docker_services_svc.deploy.resources | default(omit) }}"

- name: Persist compose into docker_services_compose_stacks[docker_services_stack_name_effective] (centralized queue)
  when: docker_services_is_deploy_host
  ansible.builtin.set_fact:
    docker_services_compose_stacks: >-
      {{
        (hostvars[docker_services_primary_manager].docker_services_compose_stacks | default({}))
        | combine({
            docker_services_stack_name_effective: (
              (hostvars[docker_services_primary_manager].docker_services_compose_stacks | default({}))
              .get(docker_services_stack_name_effective, {})
              | combine({
                  'type': (docker_services_stack_deploy_type | string | trim),
                  'docker_services_deploy_host': (docker_services_deploy_host_effective | string | trim),
                  'services': (docker_services_compose_services | default({}, true)),
                  'networks': (stack_networks | default({}, true)),
                  'volumes': (stack_volumes | default({}, true))
                }, recursive=true)
            )
          }, recursive=true)
      }}
  delegate_to: "{{ docker_services_primary_manager }}"
  delegate_facts: true
