---

################################
# PREP (PATHS)
################################

- name: Create filesystem paths (on filesystem hosts)
  when:
    - inventory_hostname == docker_services_primary_manager
    - docker_services_svc.paths is defined
    - (docker_services_svc.paths | length > 0)
  ansible.builtin.include_tasks:
    file: sub_tasks/paths.yml
    apply:
      tags: [deploy, update, recreate]
  vars:
    paths: "{{ docker_services_svc.paths }}"
    docker_services_deploy_host: "{{ _fs_target }}"
    default_owner: "{{ hostvars[_fs_target].docker_host_puid | default('1000') }}"
    default_group: "{{ hostvars[_fs_target].docker_host_pgid | default('1000') }}"
    default_mode: "0755"
  loop: "{{ docker_services_fs_hosts_effective }}"
  loop_control:
    loop_var: _fs_target
  tags: [deploy, update, recreate]

################################
# PREP (COPY FILES)
################################

- name: Copy static files (on filesystem hosts)
  when:
    - inventory_hostname == docker_services_primary_manager
    - docker_services_svc.copies is defined
    - (docker_services_svc.copies | length > 0)
  ansible.builtin.include_tasks:
    file: sub_tasks/copies.yml
    apply:
      tags: [deploy, update, recreate]
  vars:
    copies: "{{ docker_services_svc.copies }}"
    docker_services_deploy_host: "{{ _fs_target }}"
    default_owner: "{{ hostvars[_fs_target].docker_host_puid | default('1000') }}"
    default_group: "{{ hostvars[_fs_target].docker_host_pgid | default('1000') }}"
  loop: "{{ docker_services_fs_hosts_effective }}"
  loop_control:
    loop_var: _fs_target
  tags: [deploy, update, recreate]

################################
# PREP (TEMPLATES)
################################

- name: Render templates (on filesystem host)
  when:
    - inventory_hostname == docker_services_primary_manager
    - docker_services_svc.templates is defined
    - (docker_services_svc.templates | length > 0)
  ansible.builtin.include_tasks:
    file: sub_tasks/templates.yml
    apply:
      tags: [deploy, update, recreate]
  vars:
    templates: "{{ docker_services_svc.templates }}"
    docker_services_deploy_host: "{{ _fs_target }}"
    default_owner: "{{ hostvars[_fs_target].docker_host_puid | default('1000') }}"
    default_group: "{{ hostvars[_fs_target].docker_host_pgid | default('1000') }}"
  loop: "{{ docker_services_fs_hosts_effective }}"
  loop_control:
    loop_var: _fs_target
  tags: [deploy, update, recreate]

################################
# PREP (SWARM ENV TEMPLATES)
################################

- name: Render swarm env templates (always on services manager)
  when:
    - inventory_hostname == docker_services_primary_manager
    - (docker_services_stack_deploy_type | string | trim) == "swarm"
    - docker_services_svc.swarm_env_templates is defined
    - (docker_services_svc.swarm_env_templates | length > 0)
  ansible.builtin.include_tasks:
    file: sub_tasks/templates.yml
    apply:
      tags: [deploy, update, recreate]
  vars:
    templates: "{{ docker_services_svc.swarm_env_templates }}"
    docker_services_deploy_host: "{{ docker_services_primary_manager }}"
    default_owner: "{{ hostvars[docker_services_primary_manager].docker_host_puid | default('1000') }}"
    default_group: "{{ hostvars[docker_services_primary_manager].docker_host_pgid | default('1000') }}"
  tags: [deploy, update, recreate]

################################
# PREP (TEMPLATE MIDDLEWARES)
################################

- name: Render swarm env templates (always on services manager)
  when:
    - inventory_hostname == docker_services_primary_manager
    - docker_services_svc.traefik is defined
    - (docker_services_svc.traefik.enable | default(false)) | bool
  ansible.builtin.include_tasks:
    file: sub_tasks/middlewares.yml
    apply:
      tags: [deploy, update, recreate]
  tags: [deploy, update, recreate]
