---

- name: Compose user | Validate service name
  ansible.builtin.assert:
    that:
      - docker_services_service_name is defined
      - docker_services_service_name | trim | length > 0
    fail_msg: "docker_services_service_name must be set before calling this helper"

- name: Compose user | Set container user
  ansible.builtin.set_fact:
    docker_services_compose_services: >-
      {{
        (docker_services_compose_services | default({}))
        | combine({
            docker_services_service_name: (
              ((docker_services_compose_services | default({})).get(docker_services_service_name, {}))
              | combine({
                  'user': user
                }, recursive=true)
            )
          }, recursive=true)
      }}
