---

################################
# INITIALIZE
################################

- name: Docker services | Initialize service
  ansible.builtin.include_tasks:
    file: sub_tasks/init.yml
    apply:
      tags: [deploy, update, recreate, bootstrap]
  tags: [deploy, update, remove, recreate, bootstrap, drift]

################################
# IMAGE DRIFT
################################

- name: Docker services | Check image drift
  when: docker_services_is_deploy_host | bool
  ansible.builtin.include_tasks:
    file: sub_tasks/drift/image.yml
    apply:
      tags: drift
  tags: drift

################################
# PREPARE
################################

- name: Docker services | Prepare service
  ansible.builtin.include_tasks:
    file: sub_tasks/prepare.yml
    apply:
      tags: [remove, deploy, update, recreate, bootstrap]
  tags: [remove, deploy, update, recreate, bootstrap]

################################
# BUILD COMPOSE CONFIGURATION
################################

- name: Docker services | Build Compose configuration
  no_log: true
  ansible.builtin.include_tasks:
    file: sub_tasks/compose.yml
    apply:
      tags: [deploy, update, recreate]
      no_log: true
      diff: false
  tags: [deploy, update, recreate]

################################
# SAVE STACK CONFIGURATION
################################

- name: Docker services | Save stack configuration
  no_log: true
  ansible.builtin.include_tasks:
    file: sub_tasks/save_stack.yml
    apply:
      tags: [deploy, update, recreate]
      no_log: true
      diff: false
  tags: [deploy, update, recreate]
