---

################################
# INIT
################################

- name: Init | Include tasks
  ansible.builtin.include_tasks:
    file: _init.yml
    apply:
      tags: [deploy, update, recreate, bootstrap]
  tags: [deploy, update, remove, recreate, bootstrap, drift]

################################
# DRIFT
################################

- name: Drift | Include image drift check
  when: docker_services_is_deploy_host | bool
  ansible.builtin.include_tasks:
    file: sub_tasks/drift/image.yml
    apply:
      tags: drift
  tags: drift

################################
# PREP
################################

- name: Prep | Include tasks
  ansible.builtin.include_tasks:
    file: _prep.yml
    apply:
      tags: [remove, deploy, update, recreate, bootstrap]
  tags: [remove, deploy, update, recreate, bootstrap]

################################
# COMPOSE
################################

- name: Compose | Include tasks
  no_log: true
  ansible.builtin.include_tasks:
    file: _compose.yml
    apply:
      tags: [deploy, update, recreate]
      no_log: true
      diff: false
  tags: [deploy, update, recreate]

################################
# DEPLOY
################################

- name: Deploy | Include tasks
  no_log: true
  ansible.builtin.include_tasks:
    file: _deploy.yml
    apply:
      tags: [deploy, update, recreate]
      no_log: true
      diff: false
  tags: [deploy, update, recreate]
