---

################################
# INIT
################################

- name: Init | Include tasks
  ansible.builtin.include_tasks:
    file: _init.yml
    apply:
      tags: [deploy, update, recreate, bootstrap]
  tags: [deploy, update, remove, recreate, bootstrap, drift, reconcile]

################################
# DRIFT
################################

- name: Drift | Include image drift check
  when: inventory_hostname == docker_services_primary_manager
  ansible.builtin.include_tasks:
    file: sub_tasks/drift/image.yml
    apply:
      tags: [drift, reconcile]
  tags: [drift, reconcile]

################################
# PREP
################################

- name: Prep | Include tasks
  ansible.builtin.include_tasks: _prep.yml
  tags: [remove, deploy, update, recreate, bootstrap]

################################
# COMPOSE
################################

- name: Compose | Include tasks
  ansible.builtin.include_tasks:
    file: _compose.yml
    apply:
      tags: [deploy, update, recreate]
  tags: [deploy, update, recreate]

################################
# DEPLOY
################################

- name: Deploy | Include tasks
  ansible.builtin.include_tasks:
    file: _deploy.yml
    apply:
      tags: [deploy, update, recreate]
  tags: [deploy, update, recreate]
