---

- name: Render templates on deploy host
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ temp_prep.src }}"
    dest: "{{ temp_prep.dest }}"
    owner: "{{ temp_prep.owner | default(default_owner, true) }}"
    group: "{{ temp_prep.group | default(default_group, true) }}"
    mode: "{{ temp_prep.mode | default('0664', true) }}"
    force: "{{ temp_prep.force | default(true) | bool }}"
  loop: "{{ templates }}"
  loop_control:
    loop_var: temp_prep
    label: "{{ temp_prep.dest }}"
  delegate_to: "{{ docker_services_deploy_host | default('mgt') }}"
