---

- name: Create stacks directory
  ansible.builtin.file:
    path: "/opt/stacks"
    state: directory
    force: false
    owner: "{{ hostvars[_deploy_host_effective].puid | default('1000') }}"
    group: "{{ hostvars[_deploy_host_effective].pgid | default('1000') }}"
    mode: "0755"

- name: Deploy Docker container stack (compose)
  when: (deploy_stack_type | default('swarm', true)) != 'swarm'
  block:
    - name: Import compose file
      ansible.builtin.template:
        src: "{{ role_path }}/templates/compose.yml.j2"
        dest: "/opt/stacks/{{ deploy_stack_name }}-compose.yml"
        force: true
        owner: "{{ hostvars[_deploy_host_effective].puid | default('1000') }}"
        group: "{{ hostvars[_deploy_host_effective].pgid | default('1000') }}"
        mode: "0664"
      vars:
        deploy_stack_type: "{{ deploy_stack_type }}"
        stack_networks: "{{ (compose_stacks | default({})).get(deploy_stack_name, {}).get('networks', {}) | default({}, true) }}"
        stack_volumes:  "{{ (compose_stacks | default({})).get(deploy_stack_name, {}).get('volumes', {})  | default({}, true) }}"

    - name: Compose up
      community.docker.docker_compose_v2:
        project_src: "/opt/stacks"
        project_name: "{{ deploy_stack_name }}"
        files: "{{ deploy_stack_name }}-compose.yml"
        state: present

- name: Deploy Docker Swarm stack
  when: (deploy_stack_type | default('swarm', true)) == 'swarm'
  block:
    - name: Import stack file
      ansible.builtin.template:
        src: "{{ role_path }}/templates/compose.yml.j2"
        dest: "/opt/stacks/{{ deploy_stack_name }}-stack.yml"
        force: true
        owner: "{{ hostvars[_deploy_host_effective].puid | default('1000') }}"
        group: "{{ hostvars[_deploy_host_effective].pgid | default('1000') }}"
        mode: "0664"
      vars:
        deploy_stack_type: "{{ deploy_stack_type }}"
        stack_networks: "{{ (compose_stacks | default({})).get(deploy_stack_name, {}).get('networks', {}) | default({}, true) }}"
        stack_volumes:  "{{ (compose_stacks | default({})).get(deploy_stack_name, {}).get('volumes', {})  | default({}, true) }}"

    - name: Deploy stack
      community.docker.docker_stack:
        state: present
        name: "{{ deploy_stack_name }}"
        compose:
          - "/opt/stacks/{{ deploy_stack_name }}-stack.yml"
