---

infisical_name: infisical
infisical_image: infisical/infisical:v0.159.1
infisical_port: 8066
infisical_path: "/opt/{{ infisical_name }}"
infisical_enc_key: ""
infisical_jwt_key: ""

infisical_network: infisical

infisical_postgres_name: infisical-postgres
infisical_postgres_image: postgres:18.3
infisical_postgres_port: 5432
infisical_postgres_path: "{{ infisical_path }}/postgres"
infisical_postgres_user: ""
infisical_postgres_pass: ""
infisical_expose_postgres: false

infisical_redis_name: infisical-redis
infisical_redis_image: redis:8.6.2-alpine3.23
infisical_redis_port: 6390
infisical_redis_path: "{{ infisical_path }}/redis"
infisical_redis_key: ""
infisical_expose_redis: false

infisical_smtp_email: ""
infisical_smtp_host: ""
infisical_smtp_port: ""
infisical_smtp_user: ""
infisical_smtp_pass: ""
infisical_smtp_sender: ""

infisical_site_url: "http://localhost:8080"