---

- name: Create Python virtualenv
  ansible.builtin.command:
    argv:
      - python3
      - -m
      - venv
      - "{{ ubuntu_ansible_venv_path }}"
  args:
    creates: "{{ ubuntu_ansible_venv_path }}/bin/python"

- name: Upgrade pip tooling in virtualenv
  ansible.builtin.pip:
    name:
      - pip==26.0.1
      - setuptools==82.0.1
      - wheel==0.46.3
    state: present
    virtualenv: "{{ ubuntu_ansible_venv_path }}"

- name: Install Python packages in virtualenv
  ansible.builtin.pip:
    name:
      - docker==7.1.0
      - requests==2.32.5
      - PyYAML==6.0.3
      - jmespath==1.1.0
    state: present
    virtualenv: "{{ ubuntu_ansible_venv_path }}"
