---

- name: Ensure /ansible exists
  ansible.builtin.file:
    path: /ansible
    state: directory
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    mode: "0755"

- name: Create Ansible virtualenv
  ansible.builtin.command:
    argv:
      - python3
      - -m
      - venv
      - /ansible/ansible-venv
  args:
    creates: /ansible/ansible-venv/bin/python

- name: Upgrade pip tooling in Ansible virtualenv
  ansible.builtin.pip:
    name:
      - pip==25.2
      - setuptools==80.9.0
      - wheel==0.45.1
    state: present
    virtualenv: /ansible/ansible-venv

- name: Install Python packages in Ansible virtualenv
  ansible.builtin.pip:
    name:
      - docker==7.1.0
      - requests==2.32.5
      - PyYAML==6.0.3
      - jmespath==1.1.0
    state: present
    virtualenv: /ansible/ansible-venv
