---

- name: Install common apt packages
  ansible.builtin.include_tasks:
    file: _apt.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_apt
  tags:
    - ubuntu
    - ubuntu_apt

- name: Clone Homelab repo
  when: inventory_hostname in groups['ansible_managers']
  ansible.builtin.include_tasks:
    file: _repo.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_repo
  tags:
    - ubuntu
    - ubuntu_repo

- name: Setup Python venv
  when: inventory_hostname in groups['ansible_managers']
  ansible.builtin.include_tasks:
    file: _venv.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_venv
  tags:
    - ubuntu
    - ubuntu_venv

- name: Install Skynet wrapper
  when: inventory_hostname in groups['ansible_managers']
  ansible.builtin.include_tasks:
    file: _skynet.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_skynet
  tags:
    - ubuntu
    - ubuntu_skynet

- name: Tune sysctl settings
  ansible.builtin.include_tasks:
    file: _sysctl.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_sysctl
  tags:
    - ubuntu
    - ubuntu_sysctl

- name: Set PAM limits
  ansible.builtin.include_tasks:
    file: _pam.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_pam
  tags:
    - ubuntu
    - ubuntu_pam

- name: Configure network tuning
  ansible.builtin.include_tasks:
    file: _network.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_network
  tags:
    - ubuntu
    - ubuntu_network

- name: Configure Netplan
  ansible.builtin.include_tasks:
    file: _netplan.yml
    apply:
      tags:
        - ubuntu
        - ubuntu_netplan
  tags:
    - ubuntu
    - ubuntu_netplan
