---

################################
# ASSERTS
################################

- name: Infisical | Assert required non-secret values are defined
  ansible.builtin.assert:
    that:
      - infisical_domain is defined
      - infisical_domain | string | length > 0
      - infisical_base_path is defined
      - infisical_base_path | string | length > 0
      - infisical_docker_network is defined
      - infisical_docker_network | string | length > 0
    fail_msg: "Required infisical variable is missing."
  tags:
    - infisical_bootstrap
    - infisical_deploy
    - infisical_recreate

################################
# OPTIONAL CLEAN UP
################################

- name: Infisical | Check if compose file exists
  ansible.builtin.stat:
    path: "{{ infisical_compose_path }}"
  register: infisical_existing_compose_yaml
  tags:
    - infisical_recreate
    - infisical_remove

- name: Infisical | Compose down
  when: infisical_existing_compose_yaml.stat.exists
  community.docker.docker_compose_v2:
    project_src: "{{ infisical_base_path }}"
    project_name: "{{ infisical_stack }}"
    files: "{{ infisical_compose_file }}"
    state: absent
  tags:
    - infisical_recreate
    - infisical_remove

- name: Infisical | Remove compose file
  ansible.builtin.file:
    path: "{{ infisical_compose_path }}"
    state: absent
  tags:
    - infisical_recreate
    - infisical_remove

################################
# DIRECTORIES
################################

- name: Infisical | Create directories
  ansible.builtin.file:
    path: "{{ _infisical_dir.path }}"
    state: directory
    owner: "{{ _infisical_dir.owner }}"
    group: "{{ _infisical_dir.group }}"
    mode: "{{ _infisical_dir.mode }}"
  loop:
    - path: "{{ infisical_base_path }}"
      owner: "{{ infisical_puid }}"
      group: "{{ infisical_pgid }}"
      mode: "0755"
    - path: "{{ infisical_redis_path }}"
      owner: "{{ infisical_redis_puid }}"
      group: "{{ infisical_redis_pgid }}"
      mode: "0755"
  loop_control:
    loop_var: _infisical_dir
  tags:
    - infisical_bootstrap
    - infisical_deploy
    - infisical_recreate

################################
# CONFIG
################################

- name: Infisical | Template env file
  ansible.builtin.template:
    src: infisical.env.j2
    dest: "{{ infisical_env_path }}"
    force: true
    owner: root
    group: root
    mode: "0600"
  no_log: true
  tags:
    - infisical_bootstrap
    - infisical_deploy
    - infisical_recreate

################################
# SECRETS
################################

- name: Infisical | Assert Docker secrets values are defined
  ansible.builtin.assert:
    that:
      - item.value is defined
      - item.value | string | length > 0
    fail_msg: "Infisical Docker secret '{{ item.key }}' is empty or undefined."
  loop: "{{ infisical_redis_docker_secrets | dict2items }}"
  no_log: true
  tags:
    - infisical_bootstrap
    - infisical_deploy
    - infisical_recreate

- name: Infisical | Create Docker secrets directory
  ansible.builtin.file:
    path: "{{ infisical_redis_secrets_files_path }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  tags:
    - infisical_bootstrap
    - infisical_deploy
    - infisical_recreate

- name: Infisical | Create Docker secrets files
  ansible.builtin.copy:
    dest: "{{ infisical_redis_secrets_files_path }}/{{ item.key }}"
    content: "{{ item.value }}\n"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ infisical_redis_docker_secrets | dict2items }}"
  no_log: true
  tags:
    - infisical_bootstrap
    - infisical_deploy
    - infisical_recreate

################################
# TRAEFIK
################################

- name: Infisical | Render Traefik dynamic file
  ansible.builtin.template:
    src: traefik_dynamic_file.j2
    dest: "{{ infisical_traefik_dynamic_dir }}/{{ infisical_name }}-dynamic.yml"
    owner: "{{ infisical_traefik_dynamic_owner }}"
    group: "{{ infisical_traefik_dynamic_group }}"
    mode: "0644"
    force: true
  tags:
    - infisical_deploy
    - infisical_recreate

################################
# DEPLOY
################################

- name: Infisical | Import compose file
  ansible.builtin.template:
    src: infisical-compose.yml.j2
    dest: "{{ infisical_compose_path }}"
    force: true
    owner: "{{ infisical_puid }}"
    group: "{{ infisical_pgid }}"
    mode: "0664"
  tags:
    - infisical_deploy
    - infisical_recreate

- name: Infisical | Compose stack up
  community.docker.docker_compose_v2:
    project_src: "{{ infisical_base_path }}"
    files: "{{ infisical_compose_file }}"
    state: present
  tags:
    - infisical_deploy
    - infisical_recreate
