---

################################
# POSTGRES
################################

postgres_version: 18

################################
# ETCD
################################

postgres_etcd_data_dir: /var/lib/etcd
postgres_etcd_client_port: 2379
postgres_etcd_peer_port: 2380
postgres_etcd_cluster_token: pg-ha-1

#  postgres_etcd_initial_cluster: []

################################
# PATRONI
################################

postgres_patroni_scope: pg-cluster
postgres_patroni_namespace: /service
postgres_patroni_node_name: "{{ inventory_hostname }}"

postgres_patroni_config_dir: /etc/patroni
postgres_patroni_config_path: "{{ postgres_patroni_config_dir }}/config.yml"
postgres_patroni_data_dir: "/var/lib/postgresql/{{ postgres_version }}/main"
postgres_patroni_bin_dir: "/usr/lib/postgresql/{{ postgres_version }}/bin"
postgres_patroni_restapi_port: 8008
postgres_patroni_postgres_port: 5432

################################
# PG-ADMIN
################################

postgres_patroni_superuser_name: postgres
postgres_patroni_superuser_pass: ""

postgres_patroni_replication_name: replicator
postgres_patroni_replication_pass: ""

postgres_patroni_admin_role_name: admin
postgres_patroni_admin_role_pass: ""
postgres_patroni_admin_role_login: true
postgres_patroni_admin_role_createdb: true
postgres_patroni_admin_role_createrole: false

postgres_patroni_etcd_hosts: []
postgres_patroni_pg_hba_extra: []

################################
# UPTIME KUMA MONITOR USER
################################

postgres_uptime_kuma_monitor_role_name: uptime_kuma_monitor
postgres_uptime_kuma_monitor_role_pass: ""
postgres_uptime_kuma_monitor_database: postgres

################################
# BACKUP (DUMP DATABASES)
################################

  ## Example:
  #  postgres_backup_dbs:
  #    - gotify
  #    - vaultwarden
  #    - qui

postgres_backup_dir: /var/backups/postgres
postgres_backup_dbs: []
postgres_backup_dbs_dir: "{{ postgres_backup_dir }}"
postgres_backup_dbs_format: custom

################################
# RESTORE (DATABASES)
################################

postgres_restore_dbs_dir: "/var/backups/postgres"
postgres_restore_dbs_drop_existing: true

# Each entry:
# - db: target database name
#   file: dump filename or full path
postgres_restore_dbs_map: []

################################
# FIX OWNER (DATABASES)
################################

  ## Example:
  #  postgres_fix_owner_map:
  #    - db: gotify
  #      role: some_user
  #    - db: vaultwarden
  #      role: some_user
  #    - db: qui
  #      role: some_user

postgres_fix_owner_map: []
