---
podman_install_enable: true
podman_state: present
podman_update_cache: true
podman_cache_valid_time: 3600
podman_min_version: "5.7.0"
podman_quadlet_generator_paths:
  - /usr/lib/systemd/system-generators/podman-system-generator
  - /lib/systemd/system-generators/podman-system-generator
podman_packages:
  - podman
  - containernetworking-plugins
  - uidmap
  - slirp4netns
  - fuse-overlayfs
podman_install_extra_packages: []
