---

- name: Configure local workstation
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  tasks:
    - name: Include workstation role
      ansible.builtin.include_role:
        name: workstation
        apply:
          tags:
            - workstation
            - workstation_apt
            - workstation_dev
            - workstation_vscode
            - workstation_shell
            - workstation_desktop
      tags:
        - workstation
        - workstation_apt
        - workstation_dev
        - workstation_vscode
        - workstation_shell
        - workstation_desktop
