---

alloy:
  name: alloy
  stack: alloy
  image: grafana/alloy:v1.14.1
  named_networks:
    overlay:
      external: true
  command:
    - "run"
    - "--server.http.listen-addr=0.0.0.0:12345"
    - "--storage.path=/etc/alloy/data"
    - "/etc/alloy/config.alloy"
  environment:
    TZ: "{{ timezone }}"
  user: "0"
  paths:
    - path: /opt/alloy
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
    - path: /opt/alloy/data
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
  swarm_configs:
    - name: alloy_config
      src: files/alloy_config.alloy
      data_is_template: false
  configs:
    - source: alloy_config
      target: /etc/alloy/config.alloy
      mode: "0644"
  volumes:
    config:
      type: bind
      source: /opt/alloy
      target: /etc/alloy
      read_only: false
    docker_sock:
      type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
    docker_container:
      type: bind
      source: /var/lib/docker/containers
      target: /var/lib/docker/containers
      read_only: true
  traefik:
    enable: true
    port: 12345
    sso: authelia
  cloudflare:
    enable: true
  deploy:
    type: swarm
    mode: global
    replicas: 1
    host: [mgt, unraid, plex]
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
