---

alloy:
  name: alloy
  stack: alloy
  image: grafana/alloy:v1.14.0
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD"
      - "wget"
      - "--spider"
      - "-q"
      - "http://127.0.0.1:12345/-/ready"
  command:
    - "run"
    - "--server.http.listen-addr=0.0.0.0:12345"
    - "--storage.path=/etc/alloy/data"
    - "/etc/alloy/config.alloy"
  environment:
    TZ: "{{ timezone }}"
  user: "1000:1000"
  paths:
    - path: /opt/alloy
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
    - path: /opt/alloy/data
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
  templates:
    - src: configs/alloy_config.alloy.j2
      dest: /opt/alloy/config.alloy
      owner: 1000
      group: 1000
      mode: "0644"
      force: true
  volumes:
    config:
      type: bind
      source: /opt/alloy
      target: /etc/alloy
      read_only: false
    docker_sock:
      type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
  traefik:
    enable: true
    port: 12345
    sso: authelia
  cloudflare:
    enable: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: mgt
    constraints:
      - node.labels.ansible_host == mgt
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
