---

authelia_redis:
  name: authelia-redis
  stack: authelia-redis
  image: redis:8.6-alpine
  named_networks:
    overlay:
      external: true
  command:
    - sh -c 'redis-server --requirepass "$$(cat /run/secrets/authelia_redis_secret)"'
  environment:
    TZ: "{{ timezone }}"
    PUID: "1000"
    PGID: "1000"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: authelia_redis_key
        path: "/Authelia"
        name: REDIS_KEY
        docker_secret: authelia_redis_secret
  secrets:
    - authelia_redis_secret
  paths:
    - path: /opt/authelia/redis
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
  volumes:
    config:
      type: bind
      source: /opt/authelia/redis
      target: /data
      read_only: false
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: mgt
    constraints:
      - node.labels.ansible_host == mgt
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
