---

autopulse_ui:
  name: autopulse-ui
  stack: autopulse
  image: danonline/autopulse:ui@sha256:2a2686154cb5d18fdf62a5034462d6e35ed488e27ffd0fb7a1ff275dc095b9a2
  named_networks:
    overlay:
      external: true
  traefik:
    enable: true
    port: 2880
    sso: authelia
  cloudflare:
    enable: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: unraid
    constraints:
      - node.labels.ansible_host == unraid
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
