---

autopulse:
  stack: autopulse
  named_networks:
    overlay:
      external: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_unraid_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
  targets:
    user_interface:
      name: autopulse-ui
      image: danonline/autopulse:ui@sha256:f11615be8257dd52600e93f90d0e4613abf08b062cdfba46dce19c08f3cb8096
      traefik:
        enable: true
        port: 2880
        sso: authelia
      cloudflare:
        enable: true
    main:
      name: autopulse
      image: danonline/autopulse:latest-postgres@sha256:04db221fe789a43a21a0652b4b248f9905dab3fb9bdcdb263eb8ab8600c02e03
      environment:
        TZ: "{{ timezone }}"
        PUID: "{{ hostvars[docker_services_unraid_host].docker_host_puid }}"
        PGID: "{{ hostvars[docker_services_unraid_host].docker_host_pgid }}"
        UMASK: "022"
        AUTOPULSE__AUTH__USERNAME__FILE: /run/secrets/autopulse_user_secret
        AUTOPULSE__AUTH__PASSWORD__FILE: /run/secrets/autopulse_pass_secret
        AUTOPULSE__TARGETS__PLEX__TOKEN__FILE: /run/secrets/plex_token_secret
      env_file:
        - /opt/stacks/autopulse.env
      infisical:
        fail_on_empty: true
        secrets_map:
          - var: autopulse_user
            path: "/Autopulse"
            name: USER
            docker_secret: autopulse_user_secret
          - var: autopulse_pass
            path: "/Autopulse"
            name: PASS
            docker_secret: autopulse_pass_secret
          - var: plex_token
            path: "/Plex"
            name: TOKEN
            docker_secret: plex_token_secret
      secrets:
        - autopulse_user_secret
        - autopulse_pass_secret
        - plex_token_secret
      paths:
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/autopulse"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/autopulse/config.yaml"
          state: touch
          mode: "0664"
      swarm_env_templates:
        - src: configs/autopulse.env.j2
          dest: /opt/stacks/autopulse.env
          mode: "0600"
          force: true
      volumes:
        config:
          type: bind
          source: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/autopulse/config.yaml"
          target: /app/config.yaml
          read_only: false
      postgres:
        enable: true
        databases:
          - "autopulse"
