---

autopulse_ui:
  name: autopulse-ui
  stack: autopulse
  image: danonline/autopulse:ui@sha256:0afcb9fa36016fd49ca48d7dfb5fa0cbc9ecfa05c141c5079952dfbb755febe4
  named_networks:
    overlay:
      external: true
  traefik:
    enable: true
    port: 2880
    sso: authelia
  cloudflare:
    enable: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_unraid_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
