---

cross_seed:
  name: cross-seed
  stack: cross-seed
  image: ghcr.io/cross-seed/cross-seed:master@sha256:b570bfa5e62804a74428326c3751e8384f1352168dafcd1ce396c02b53d0f65e
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD"
      - "wget"
      - "--spider"
      - "-q"
      - "http://127.0.0.1:2468/api/ping"
  user: "99:100"
  environment:
    TZ: "{{ timezone }}"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: cross_seed_api
        path: "/Cross-Seed"
        name: API
      - var: cross_seed_notifiarr_webhook
        path: "/Cross-Seed"
        name: NOTIFIARR_WEBHOOK
      - var: qbittorrent_xs_user
        path: "/qBittorrent-XS"
        name: USER
      - var: qbittorrent_xs_pass
        path: "/qBittorrent-XS"
        name: PASS
      - var: prowlarr_api
        path: "/Prowlarr"
        name: API
      - var: radarr_api
        path: "/Radarr"
        name: API
      - var: radarr_4k_api
        path: "/Radarr-4K"
        name: API
      - var: sonarr_api
        path: "/Sonarr"
        name: API
      - var: sonarr_4k_api
        path: "/Sonarr-4K"
        name: API
  paths:
    - path: /mnt/user/appdata/cross-seed
      state: directory
      owner: 99
      group: 100
      mode: "0755"
    - path: /mnt/user/data/seeds
      state: directory
      owner: 99
      group: 100
      mode: "0755"
    - path: /mnt/user/data/seeds/links
      state: directory
      owner: 99
      group: 100
      mode: "0755"
  templates:
    - src: configs/cross_seed_config.j2
      dest: /mnt/user/appdata/cross-seed/config.js
      owner: 99
      group: 100
      mode: "0664"
      force: true
  volumes:
    config:
      type: bind
      source: /mnt/user/appdata/cross-seed
      target: /config
      read_only: false
    media:
      type: bind
      source: /mnt/user/data
      target: /data
      read_only: false
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: unraid
    constraints:
      - node.labels.ansible_host == unraid
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
