---

gitea:
  name: gitea
  stack: gitea
  image: gitea/gitea:1.25.5
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD"
      - "wget"
      - "--spider"
      - "-q"
      - "http://127.0.0.1:3000/api/healthz"
  environment:
    TZ: "{{ timezone }}"
    USER_UID: "{{ hostvars[docker_services_primary_manager].docker_host_puid }}"
    USER_GID: "{{ hostvars[docker_services_primary_manager].docker_host_pgid }}"
    UMASK: "022"
  env_file:
    - "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/gitea/.env"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: postgres_user
        path: "/Postgres"
        name: USER
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/gitea"
      state: directory
      mode: "0755"
  templates:
    - src: configs/gitea.env.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/gitea/.env"
      mode: "0664"
      force: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/gitea"
      target: /data
      read_only: false
  postgres:
    enable: true
    databases:
      - gitea
  traefik:
    enable: true
    port: 3000
    sso: authelia
  cloudflare:
    enable: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
