---

gotify:
  name: gotify
  stack: gotify
  image: gotify/server:2.9.1
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars[docker_services_primary_manager].docker_host_puid }}"
    PGID: "{{ hostvars[docker_services_primary_manager].docker_host_pgid }}"
  env_file:
    - "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/gotify/.env"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: postgres_user
        path: "/Postgres"
        name: USER
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/gotify"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/gotify/images"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/gotify/plugins"
      state: directory
      mode: "0755"
  templates:
    - src: configs/gotify.env.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/gotify/.env"
      mode: "0664"
      force: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/gotify"
      target: /app/data
      read_only: false
  postgres:
    enable: true
    databases:
      - gotify
  traefik:
    enable: true
    port: 80
  cloudflare:
    enable: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
