---

hugo:
  name: hugo
  stack: hugo
  image: ghcr.io/gohugoio/hugo:v0.158.0
  named_networks:
    overlay:
      external: true
  command:
    - "server -D"
  environment:
    TZ: "{{ timezone }}"
    PUID: "1000"
    PGID: "1000"
    UMASK: "022"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: cloudflare_zone
        path: "/Hugo"
        name: DOMAIN
      - var: github_email
        path: "/Hugo"
        name: GITHUB_EMAIL
      - var: github_username
        path: "/Hugo"
        name: GITHUB_USER
  ports:
    web:
      published: 1313
      target: 1313
      protocol: tcp
      mode: ingress
  paths:
    - path: /opt/hugo
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
    - path: /home/mgt/blog
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
    - path: /home/mgt/blog/.github
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
    - path: /home/mgt/blog/.github/workflows
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
  copies:
    - src: files/hugo/favicon.png
      dest: /home/mgt/blog/static/favicon.png
      owner: 1000
      group: 1000
      mode: "0664"
      force: false
      wait: true
      wait_timeout: 30
    - src: files/hugo/og-image.png
      dest: /home/mgt/blog/static/og-image.png
      owner: 1000
      group: 1000
      mode: "0664"
      force: false
      wait: true
      wait_timeout: 30
    - src: files/hugo/terminal.css
      dest: /home/mgt/blog/static/terminal.css
      owner: 1000
      group: 1000
      mode: "0664"
      force: false
      wait: true
      wait_timeout: 30
    - src: files/hugo/pages.yaml
      dest: /home/mgt/blog/.github/workflows/hugo.yaml
      owner: 1000
      group: 1000
      mode: "0664"
      force: false
      wait: true
      wait_timeout: 30
  templates:
    - src: configs/hugo.yaml.j2
      dest: /home/mgt/blog/hugo.yaml
      owner: 1000
      group: 1000
      mode: "0664"
      force: true
  volumes:
    cache:
      type: bind
      source: /opt/hugo
      target: /cache
      read_only: false
    blog:
      type: bind
      source: /home/mgt/blog
      target: /project
      read_only: false
  cloudflare:
    enable: true
    records:
      ## github pages addresses
      - record: "@"
        type: "A"
        value: "185.199.108.153"
        proxy: false
        solo: true
      - record: "@"
        type: "A"
        value: "185.199.109.153"
        proxy: false
        solo: true
      - record: "@"
        type: "A"
        value: "185.199.110.153"
        proxy: false
        solo: true
      - record: "@"
        type: "A"
        value: "185.199.111.153"
        proxy: false
        solo: true
      - record: "@"
        type: "AAAA"
        value: "2606:50c0:8000::153"
        proxy: false
        solo: true
      - record: "@"
        type: "AAAA"
        value: "2606:50c0:8001::153"
        proxy: false
        solo: true
      - record: "@"
        type: "AAAA"
        value: "2606:50c0:8002::153"
        proxy: false
        solo: true
      - record: "@"
        type: "AAAA"
        value: "2606:50c0:8003::153"
        proxy: false
        solo: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: mgt
    constraints:
      - node.labels.ansible_host == mgt
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
