---

lidarr:
  name: lidarr
  stack: arrs
  image: ghcr.io/hotio/lidarr:release-3.1.0.4875
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD-SHELL"
      - "touch /data/media/music/.healthcheck && rm -f /data/media/music/.healthcheck || exit 1"
  environment:
    TZ: "{{ timezone }}"
    PUID: "99"
    PGID: "100"
    UMASK: "022"
    LIDARR__APP__INSTANCENAME: "Lidarr"
    LIDARR__SERVER__PORT: "8686"
    LIDARR__AUTH__METHOD: "External"
    FILE__LIDARR__AUTH__APIKEY: /run/secrets/lidarr_api_secret
    LIDARR__POSTGRES__HOST: "spilo"
    LIDARR__POSTGRES__PORT: "5433"
    FILE__LIDARR__POSTGRES__USER: /run/secrets/postgres_user_secret
    FILE__LIDARR__POSTGRES__PASSWORD: /run/secrets/postgres_pass_secret
    LIDARR__POSTGRES__MAINDB: "lidarr-main"
    LIDARR__POSTGRES__LOGDB: "lidarr-log"
    TP_SCHEME: "http"
    TP_DOMAIN: "192.168.80.45:8089"
    TP_HOTIO: "true"
    TP_THEME: "hotline"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: lidarr_api
        path: "/Lidarr"
        name: API
        docker_secret: lidarr_api_secret
      - var: postgres_user
        path: "/Postgres"
        name: USER
        docker_secret: postgres_user_secret
      - var: postgres_pass
        path: "/Postgres"
        name: PASS
        docker_secret: postgres_pass_secret
  secrets:
    - lidarr_api_secret
    - postgres_user_secret
    - postgres_pass_secret
  paths:
    - path: /mnt/user/appdata/lidarr
      state: directory
      owner: 99
      group: 100
      mode: "0755"
  copies:
    - src: files/themepark/98-themepark-lidarr
      dest: /mnt/user/appdata/lidarr/98-themepark-lidarr
      owner: 99
      group: 100
      mode: "0755"
      force: false
      wait: true
      wait_timeout: 30
  volumes:
    config:
      type: bind
      source: /mnt/user/appdata/lidarr
      target: /config
      read_only: false
    media:
      type: bind
      source: /mnt/user/data
      target: /data
      read_only: false
    themepark:
      type: bind
      source: /mnt/user/appdata/lidarr/98-themepark-lidarr
      target: /etc/cont-init.d/98-themepark
      read_only: false
  traefik:
    enable: true
    port: 8686
    sso: authelia
    internal_api: true
    internal_api_rules:
      - "PathPrefix(`/api`)"
      - "PathPrefix(`/feed`)"
      - "PathPrefix(`/ping`)"
  themepark:
    app: lidarr
    theme: hotline
  postgres:
    enable: true
    databases:
      - lidarr-main
      - lidarr-log
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: unraid
    constraints:
      - node.labels.ansible_host == unraid
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
