---

loki:
  name: loki
  stack: loki
  image: grafana/loki:3.7.1
  named_networks:
    overlay:
      external: true
  command:
    - "-config.file=/etc/loki/loki-config.yaml"
  user: >-
    {{ hostvars[docker_services_primary_manager].docker_host_puid }}:{{ hostvars[docker_services_primary_manager].docker_host_pgid }}
  environment:
    TZ: "{{ timezone }}"
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/loki"
      state: directory
      mode: "0755"
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/loki/data"
      state: directory
      mode: "0755"
  templates:
    - src: configs/loki-config.yaml.j2
      dest: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/loki/loki-config.yaml"
      mode: "0644"
      force: true
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/loki"
      target: /etc/loki
      read_only: true
    data:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/loki/data"
      target: /loki
      read_only: false
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
