---

mariadb:
  name: mariadb
  stack: mariadb
  image: mariadb:12
  named_networks:
    overlay:
      external: true
  user: >-
    {{ hostvars[docker_services_primary_manager].docker_host_puid }}:{{ hostvars[docker_services_primary_manager].docker_host_pgid }}
  environment:
    TZ: "{{ timezone }}"
    MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_pass_secret
    MARIADB_USER: "mariadb"
    MARIADB_PASSWORD_FILE: /run/secrets/mariadb_pass_secret
    MARIADB_DATABASE: "default"
    MARIADB_AUTO_UPGRADE: "1"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: mariadb_pass
        path: "/MariaDB"
        name: PASS
        docker_secret: mariadb_pass_secret
  secrets:
    - mariadb_pass_secret
  paths:
    - path: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/mariadb"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars[docker_services_primary_manager].docker_host_appdata_root }}/mariadb"
      target: /var/lib/mysql
      read_only: false
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_primary_manager }}"
    constraints:
      - node.labels.docker_services_host == docker_services_primary_manager
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
