---

obsidian:
  name: obsidian
  stack: obsidian
  image: lscr.io/linuxserver/obsidian:v1.12.4-ls116
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD"
      - "curl"
      - "--fail"
      - "http://localhost:1314"
  environment:
    TZ: "{{ timezone }}"
    PUID: "1000"
    PGID: "1000"
    UMASK: "022"
    CUSTOM_PORT: "1314"
    CUSTOM_HTTPS_PORT: "1315"
  paths:
    - path: /opt/obsidian
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
    - path: /opt/obsidian/vault
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
    - path: /opt/obsidian/vault/posts
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
  volumes:
    config:
      type: bind
      source: /opt/obsidian
      target: /config
      read_only: false
  shm_size: 2gb
  shm_tmpfs_size: 1073741824
  traefik:
    enable: true
    port: 1314
    sso: authelia
  cloudflare:
    enable: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: mgt
    constraints:
      - node.labels.ansible_host == mgt
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
