---

portainer_agent:
  name: agent
  stack: portainer
  image: portainer/agent:2.39.0-linux-amd64-alpine
  named_networks:
    overlay:
      external: true
  volumes:
    docker_volumes:
      type: bind
      source: /var/lib/docker/volumes
      target: /var/lib/docker/volumes
    docker_sock:
      type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  deploy:
    type: swarm
    mode: global
    constraints:
      - node.platform.os == linux
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
