---

qbittorrent:
  image: ghcr.io/hotio/qbittorrent:release-5.1.4
  stack: qbittorrent
  named_networks:
    overlay:
      external: true
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun:/dev/net/tun"
  sysctls:
    net.ipv4.conf.all.src_valid_mark: "1"
    net.ipv6.conf.all.disable_ipv6: "1"
  environment:
    PUID: "{{ hostvars[docker_services_unraid_host].docker_host_puid | string }}"
    PGID: "{{ hostvars[docker_services_unraid_host].docker_host_pgid | string }}"
    TZ: "{{ timezone }}"
    FILE__VPN_PIA_USER: /run/secrets/qbittorrent_pia_user_secret
    FILE__VPN_PIA_PASS: /run/secrets/qbittorrent_pia_pass_secret
  secrets:
    - qbittorrent_pia_user_secret
    - qbittorrent_pia_pass_secret
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: "{{ docker_services_unraid_host }}"
    constraints:
      - node.labels.docker_services_host == docker_services_unraid_host
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
  targets:
    downloads:
      name: qbittorrent
      hostname: qbittorrent.internal
      healthcheck:
        test:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - "http://127.0.0.1:8090/"
      env_file:
        - /opt/stacks/qbittorrent.env
      infisical:
        fail_on_empty: true
        secrets_map:
          - var: qbittorrent_user
            path: "/qBittorrent"
            name: USER
          - var: qbittorrent_pass
            path: "/qBittorrent"
            name: PASS
          - var: qbittorrent_pia_user
            path: "/PIA"
            name: USER
            docker_secret: qbittorrent_pia_user_secret
          - var: qbittorrent_pia_pass
            path: "/PIA"
            name: PASS
            docker_secret: qbittorrent_pia_pass_secret
      paths:
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/qbittorrent"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/qbittorrent/config"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/qbittorrent/wireguard"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}/torrents"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}/torrents/completed"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}/torrents/incoming"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}/torrents/watched"
          state: directory
          mode: "0755"
      templates:
        - src: configs/qbittorrent/qBittorrent.conf.j2
          dest: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/qbittorrent/config/qBittorrent.conf"
          mode: "0664"
          force: true
      swarm_env_templates:
        - src: configs/qbittorrent/qBittorrent.env.j2
          dest: /opt/stacks/qbittorrent.env
          owner: 1000
          group: 1000
          mode: "0600"
          force: true
      volumes:
        config:
          type: bind
          source: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/qbittorrent"
          target: /config
          read_only: false
        media:
          type: bind
          source: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}/torrents"
          target: /data/torrents
          read_only: false
      traefik:
        enable: true
        port: 8090
        sso: authelia
        internal_api: true
        internal_api_rules:
          - "PathPrefix(`/api`)"
          - "PathPrefix(`/command`)"
          - "PathPrefix(`/query`)"
          - "PathPrefix(`/login`)"
          - "PathPrefix(`/sync`)"
      cloudflare:
        enable: true
    seeds:
      name: qbittorrent-xs
      hostname: qbittorrent-xs.internal
      healthcheck:
        test:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - "http://127.0.0.1:8091/"
      env_file:
        - /opt/stacks/qbittorrent-xs.env
      infisical:
        fail_on_empty: true
        secrets_map:
          - var: qbittorrent_xs_user
            path: "/qBittorrent-XS"
            name: USER
          - var: qbittorrent_xs_pass
            path: "/qBittorrent-XS"
            name: PASS
          - var: qbittorrent_pia_user
            path: "/PIA"
            name: USER
            docker_secret: qbittorrent_pia_user_secret
          - var: qbittorrent_pia_pass
            path: "/PIA"
            name: PASS
            docker_secret: qbittorrent_pia_pass_secret
      paths:
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/qbittorrent-xs"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/qbittorrent-xs/config"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/qbittorrent-xs/wireguard"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}/seeds"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}/seeds/completed"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}/seeds/incoming"
          state: directory
          mode: "0755"
        - path: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}/seeds/watched"
          state: directory
          mode: "0755"
      templates:
        - src: configs/qbittorrent/qBittorrent-xs.conf.j2
          dest: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/qbittorrent-xs/config/qBittorrent.conf"
          mode: "0664"
          force: true
      swarm_env_templates:
        - src: configs/qbittorrent/qBittorrent-xs.env.j2
          dest: /opt/stacks/qbittorrent-xs.env
          owner: 1000
          group: 1000
          mode: "0600"
          force: true
      volumes:
        config:
          type: bind
          source: "{{ hostvars[docker_services_unraid_host].docker_host_appdata_root }}/qbittorrent-xs"
          target: /config
          read_only: false
        media:
          type: bind
          source: "{{ hostvars[docker_services_unraid_host].docker_host_data_root }}/seeds"
          target: /data/seeds
          read_only: false
      traefik:
        enable: true
        port: 8091
        sso: authelia
        internal_api: true
        internal_api_rules:
          - "PathPrefix(`/api`)"
          - "PathPrefix(`/command`)"
          - "PathPrefix(`/query`)"
          - "PathPrefix(`/login`)"
          - "PathPrefix(`/sync`)"
      cloudflare:
        enable: true
