---

services_90_gluetun:

################################
# GLUETUN
################################
  gluetun:
    name: gluetun
    stack: gluetun
    container_name: gluetun
    image: qmcgaw/gluetun:v3.41.0
    named_networks:
      overlay:
        external: true
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      TZ: "{{ timezone }}"
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      FIREWALL_OUTBOUND_SUBNETS: "192.168.80.0/24"
      UPDATER_PERIOD: "24h"
      BLOCK_MALICIOUS: "off"
      VPN_SERVICE_PROVIDER: "protonvpn"
      VPN_TYPE: "wireguard"
      WIREGUARD_ADDRESSES: "{{ gluetun_wg_addresses | default('__INFISICAL__:gluetun_wg_addresses', true) }}"
      WIREGUARD_PRIVATE_KEY: "{{ gluetun_wg_private_key | default('__INFISICAL__:gluetun_wg_private_key', true) }}"
      SERVER_COUNTRIES: "Netherlands,Germany,Poland,Switzerland"
      PORT_FORWARD_ONLY: "on"
      VPN_PORT_FORWARDING: "on"
    infisical:
      fail_on_empty: true
      secrets_map:
        - { var: gluetun_wg_addresses, path: "/Gluetun", name: "WG_ADDRESSES" }
        - { var: gluetun_wg_private_key, path: "/Gluetun", name: "WG_PRIVATE_KEY" }
    ports:
      web:
        published: 6881
        target: 6881
        protocol: tcp
        mode: ingress
      jd2_web:
        published: 5800
        target: 5800
        protocol: tcp
        mode: ingress
      librewolf_web:
        published: 3008
        target: 3000
        protocol: tcp
        mode: ingress
      librewolf_web_secure:
        published: 3009
        target: 3001
        protocol: tcp
        mode: ingress
    paths:
      - path: /mnt/user/appdata/gluetun
        state: directory
        owner: 99
        group: 100
        mode: 0755
      - path: /mnt/user/data/media/gluetun
        state: directory
        owner: 99
        group: 100
        mode: 0755
    volumes:
      config:
        type: bind
        source: /mnt/user/appdata/gluetun
        target: /gluetun
        read_only: false
    deploy:
      type: container
      host: unraid
################################
# JDOWNLOADER-2
################################
  jdownloader2:
    name: jdownloader-2
    stack: gluetun
    container_name: jdownloader-2
    image: jlesage/jdownloader-2:v26.01.1
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      USER_ID: "99"
      GROUP_ID: "100"
    paths:
      - path: /mnt/user/appdata/jdownloader-2
        state: directory
        owner: 99
        group: 100
        mode: 0755
    volumes:
      config:
        type: bind
        source: /mnt/user/appdata/jdownloader-2
        target: /config
        read_only: false
      downloads:
        type: bind
        source: /mnt/user/data/media/jdownloader-2
        target: /downloads
        read_only: false
    deploy:
      type: container
      host: unraid
################################
# LIBREWOLF
################################
  librewolf:
    name: librewolf
    stack: gluetun
    container_name: librewolf
    image: lscr.io/linuxserver/librewolf:147.0.3-2-ls127
    security_opt:
      - "seccomp:unconfined"
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      PUID: "99"
      PGID: "100"
      LIBREWOLF_CLI: "http://192.168.80.20:3075"
    paths:
      - path: /mnt/user/appdata/librewolf
        state: directory
        owner: 99
        group: 100
        mode: 0755
    volumes:
      config:
        type: bind
        source: /mnt/user/appdata/librewolf
        target: /config
        read_only: false
      downloads:
        type: bind
        source: /mnt/user/data/media/gluetun
        target: /downloads
        read_only: false
    shm_size: 1gb
    deploy:
      type: container
      host: unraid