---

services_70_monitoring:
################################
# ALLOY
################################
  alloy:
    name: alloy
    stack: alloy
    image: grafana/alloy:v1.13.1
    named_networks:
      overlay:
        external: true
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "--spider"
        - "-q"
        - "http://127.0.0.1:12345/-/ready"
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/etc/alloy/data"
      - "/etc/alloy/config.alloy"
    environment:
      TZ: "{{ timezone }}"
      PUID: "1000"
      PGID: "1000"
      UMASK: "022"
    ports:
      web:
        published: 12345
        target: 12345
        protocol: tcp
        mode: ingress
    directories:
      - path: /opt/alloy
        owner: 1000
        group: 1000
        mode: 0755
      - path: /opt/alloy/data
        owner: 1000
        group: 1000
        mode: 0755
    templates:
      - src: configs/monitoring/alloy_config.alloy.j2
        dest: /opt/alloy/config.alloy
        owner: 1000
        group: 1000
        mode: 0664
        force: true
    volumes:
      config:
        type: bind
        source: /opt/alloy
        target: /etc/alloy
        read_only: false
      rootfs:
        type: bind
        source: /
        target: /rootfs
        read_only: true
      run:
        type: bind
        source: /run
        target: /run
        read_only: true
      udev:
        type: bind
        source: /run/udev/data
        target: /run/udev/data
        read_only: true
      sys:
        type: bind
        source: /sys
        target: /sys
        read_only: true
      var_log:
        type: bind
        source: /var/log
        target: /var/log
        read_only: true
      var_lib_docker:
        type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true
    traefik:
      enable: true
      port: 12345
      sso: authelia
    deploy:
      type: swarm
      mode: replicated
      replicas: 1
      host: localhost
      constraints: 
        - node.labels.ansible_host == localhost
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 2m  
################################
# GRAFANA
################################
  grafana:
    name: "grafana"
    image: "grafana/grafana-oss:main-ubuntu"
    named_networks:
      overlay:
        external: true
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "--spider"
        - "-q"
        - "http://127.0.0.1:3000/api/health"
    user: "0"
    environment:
      TZ: "{{ timezone }}"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      UMASK: "022"
      GF_SECURITY_ADMIN_USER__FILE: /run/secrets/grafana_admin_user_secret
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_pass_secret
    infisical:
      fail_on_empty: true
      secrets_map:
        - { var: grafana_user, path: "/Grafana", name: "USER" }
        - { var: grafana_pass, path: "/Grafana", name: "PASS" }
    secrets:
      - grafana_admin_user_secret
      - grafana_admin_pass_secret
    ports:
      web:
        published: 3000
        target: 3000
        protocol: tcp
        mode: ingress
    directories:
      - path: "/opt/grafana"
        owner: "{{ puid }}"
        group: "{{ pgid }}"
        mode: "0755"
    volumes:
      config:
        type: bind
        source: "/opt/grafana"
        target: "/var/lib/grafana"
        read_only: false
    traefik:
      enable: true
      api_rule: ""
    deploy:
      type: "swarm"
      mode: "replicated"
      replicas: "1"
      host: "localhost"
      constraints:
        - "node.labels.ansible_host == localhost"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 2m

################################
# PROMETHEUS
################################
  prometheus:
    name: "prometheus"
    stack: prometheus
    image: "prom/prometheus:main"
    named_networks:
      overlay:
        external: true
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "--spider"
        - "-q"
        - "http://127.0.0.1:9090/-/ready"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    user: "1000:1000"
    environment:
      TZ: "{{ timezone }}"
    paths:
      - path: /opt/prometheus
        state: directory
        owner: 1000
        group: 1000
        mode: 0755
      - path: /opt/prometheus/data
        state: directory
        owner: 1000
        group: 1000
        mode: 0755
    templates:
      - src: configs/monitoring/prometheus.yml.j2
        dest: /opt/prometheus/prometheus.yml
        owner: 1000
        group: 1000
        mode: 0664
        force: true
    volumes:
      config:
        type: bind
        source: /opt/prometheus
        target: /etc/prometheus
        read_only: false
      data:
        type: bind
        source: /opt/prometheus/data
        target: /prometheus
        read_only: false
    traefik:
      enable: true
      port: 9090
      sso: authelia
    deploy:
      type: swarm
      mode: replicated
      replicas: 1
      host: localhost
      constraints:
        - node.labels.ansible_host == localhost
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 2m