---

sonarr:
  stack: arrs
  image: ghcr.io/hotio/sonarr:release-4.0.16.2944
  named_networks:
    overlay:
      external: true
  traefik:
    enable: true
    port: 8989
    sso: authelia
    internal_api: true
    internal_api_rules:
      - "PathPrefix(`/api`)"
      - "PathPrefix(`/feed`)"
      - "PathPrefix(`/ping`)"
  themepark:
    app: sonarr
    theme: hotline
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: unraid
    constraints:
      - node.labels.ansible_host == unraid
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
  targets:
    sonarr:
      name: sonarr
      healthcheck:
        test:
          - "CMD-SHELL"
          - "touch /data/media/tv/.healthcheck && rm -f /data/media/tv/.healthcheck || exit 1"
      environment:
        TZ: "{{ timezone }}"
        PUID: "99"
        PGID: "100"
        UMASK: "022"
        SONARR__APP__INSTANCENAME: "Sonarr"
        SONARR__SERVER__PORT: "8989"
        SONARR__AUTH__METHOD: "External"
        FILE__SONARR__AUTH__APIKEY: /run/secrets/sonarr_api_secret
        SONARR__POSTGRES__HOST: "spilo"
        SONARR__POSTGRES__PORT: "5433"
        FILE__SONARR__POSTGRES__USER: /run/secrets/postgres_user_secret
        FILE__SONARR__POSTGRES__PASSWORD: /run/secrets/postgres_pass_secret
        SONARR__POSTGRES__MAINDB: "sonarr-main"
        SONARR__POSTGRES__LOGDB: "sonarr-log"
        TP_SCHEME: "http"
        TP_DOMAIN: "192.168.80.45:8089"
        TP_HOTIO: "true"
        TP_THEME: "hotline"
      infisical:
        fail_on_empty: true
        secrets_map:
          - var: sonarr_api
            path: "/Sonarr"
            name: API
            docker_secret: sonarr_api_secret
          - var: postgres_user
            path: "/Postgres"
            name: USER
            docker_secret: postgres_user_secret
          - var: postgres_pass
            path: "/Postgres"
            name: PASS
            docker_secret: postgres_pass_secret
      secrets:
        - sonarr_api_secret
        - postgres_user_secret
        - postgres_pass_secret
      paths:
        - path: /mnt/user/appdata/sonarr
          state: directory
          owner: 99
          group: 100
          mode: "0755"
      copies:
        - src: files/themepark/98-themepark-sonarr
          dest: /mnt/user/appdata/sonarr/98-themepark-sonarr
          owner: 99
          group: 100
          mode: "0755"
          force: false
          wait: true
          wait_timeout: 30
      volumes:
        config:
          type: bind
          source: /mnt/user/appdata/sonarr
          target: /config
          read_only: false
        media:
          type: bind
          source: /mnt/user/data
          target: /data
          read_only: false
        themepark:
          type: bind
          source: /mnt/user/appdata/sonarr/98-themepark-sonarr
          target: /etc/cont-init.d/98-themepark
          read_only: false
      postgres:
        enable: true
        databases:
          - sonarr-main
          - sonarr-log
    sonarr_4k:
      name: sonarr-4k
      healthcheck:
        test:
          - "CMD-SHELL"
          - "touch /data/media/tv-4k/.healthcheck && rm -f /data/media/tv-4k/.healthcheck || exit 1"
      environment:
        TZ: "{{ timezone }}"
        PUID: "99"
        PGID: "100"
        UMASK: "022"
        SONARR__APP__INSTANCENAME: "Sonarr-4K"
        SONARR__SERVER__PORT: "8989"
        SONARR__AUTH__METHOD: "External"
        FILE__SONARR__AUTH__APIKEY: /run/secrets/sonarr_4k_api_secret
        SONARR__POSTGRES__HOST: "spilo"
        SONARR__POSTGRES__PORT: "5433"
        FILE__SONARR__POSTGRES__USER: /run/secrets/postgres_user_secret
        FILE__SONARR__POSTGRES__PASSWORD: /run/secrets/postgres_pass_secret
        SONARR__POSTGRES__MAINDB: "sonarr-4k-main"
        SONARR__POSTGRES__LOGDB: "sonarr-4k-log"
        TP_SCHEME: "http"
        TP_DOMAIN: "192.168.80.45:8089"
        TP_HOTIO: "true"
        TP_THEME: "hotline"
      infisical:
        fail_on_empty: true
        secrets_map:
          - var: sonarr_4k_api
            path: "/Sonarr-4K"
            name: API
            docker_secret: sonarr_4k_api_secret
          - var: postgres_user
            path: "/Postgres"
            name: USER
            docker_secret: postgres_user_secret
          - var: postgres_pass
            path: "/Postgres"
            name: PASS
            docker_secret: postgres_pass_secret
      secrets:
        - sonarr_4k_api_secret
        - postgres_user_secret
        - postgres_pass_secret
      paths:
        - path: /mnt/user/appdata/sonarr-4k
          state: directory
          owner: 99
          group: 100
          mode: "0755"
      copies:
        - src: files/themepark/98-themepark-sonarr
          dest: /mnt/user/appdata/sonarr-4k/98-themepark-sonarr
          owner: 99
          group: 100
          mode: "0755"
          force: false
          wait: true
          wait_timeout: 30
      volumes:
        config:
          type: bind
          source: /mnt/user/appdata/sonarr-4k
          target: /config
          read_only: false
        media:
          type: bind
          source: /mnt/user/data
          target: /data
          read_only: false
        themepark:
          type: bind
          source: /mnt/user/appdata/sonarr-4k/98-themepark-sonarr
          target: /etc/cont-init.d/98-themepark
          read_only: false
      postgres:
        enable: true
        databases:
          - sonarr-4k-main
          - sonarr-4k-log
