---

syncthing:
  name: syncthing
  stack: syncthing
  image: lscr.io/linuxserver/syncthing:v2.0.15-ls211
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    PUID: "99"
    PGID: "100"
    UMASK: "022"
  ports:
    listening_tcp:
      published: 22000
      target: 22000
      mode: host
    listening_udp:
      published: 22000
      target: 22000
      protocol: udp
      mode: host
    discovery:
      published: 21027
      target: 21027
      protocol: udp
      mode: host
  paths:
    - path: /mnt/user/appdata/syncthing
      state: directory
      owner: 99
      group: 100
      mode: "0755"
  volumes:
    config:
      type: bind
      source: /mnt/user/appdata/syncthing
      target: /config
      read_only: false
    media:
      type: bind
      source: /mnt/user/data
      target: /data
      read_only: false
  traefik:
    enable: true
    port: 8384
    sso: authelia
  cloudflare:
    enable: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: unraid
    constraints:
      - node.labels.ansible_host == unraid
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
