---

tautulli:
  name: tautulli
  stack: tautulli
  image: ghcr.io/hotio/tautulli:release-v2.16.1
  named_networks:
    overlay:
      external: true
  healthcheck:
    test:
      - "CMD"
      - "wget"
      - "--spider"
      - "-q"
      - "http://127.0.0.1:8181/status"
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars['plex'].docker_host_puid | string }}"
    PGID: "{{ hostvars['plex'].docker_host_pgid | string }}"
    UMASK: "022"
    WEBUI_PORTS: "8181/tcp,8181/udp"
    TP_SCHEME: "http"
    TP_DOMAIN: "192.168.80.48:8089"
    TP_HOTIO: "true"
    TP_THEME: "hotline"
  paths:
    - path: "{{ hostvars['plex'].docker_host_appdata_root }}/tautulli"
      state: directory
      mode: "0755"
  copies:
    - src: files/themepark/98-themepark-tautulli
      dest: "{{ hostvars['plex'].docker_host_appdata_root }}/tautulli/98-themepark-tautulli"
      mode: "0755"
      force: false
      wait: true
      wait_timeout: 30
  volumes:
    config:
      type: bind
      source: "{{ hostvars['plex'].docker_host_appdata_root }}/tautulli"
      target: /config
      read_only: false
    themepark:
      type: bind
      source: "{{ hostvars['plex'].docker_host_appdata_root }}/tautulli/98-themepark-tautulli"
      target: /etc/cont-init.d/98-themepark
      read_only: false
  traefik:
    enable: true
    port: 8181
    sso: authelia
    internal_api: true
    internal_api_rules:
      - "PathPrefix(`/api`)"
      - "PathPrefix(`/newsletter`)"
      - "PathPrefix(`/image`)"
      - "PathPrefix(`/pms_image_proxy`)"
  cloudflare:
    enable: true
  themepark:
    app: tautulli
    theme: hotpink
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: plex
    constraints:
      - node.labels.ansible_host == plex
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
