---

unifi_db:
  name: unifi-db
  stack: unifi
  image: docker.io/mongo:8.2
  named_networks:
    overlay:
      external: true
  user: "1000:1000"
  environment:
    TZ: "{{ timezone }}"
    MONGO_INITDB_ROOT_USERNAME: "root"
    MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/unifi_db_root_pass_secret
    MONGO_USER: "{{ unifi_db_user | default('__INFISICAL__:unifi_db_user', true) }}"
    MONGO_PASS: "{{ unifi_db_pass | default('__INFISICAL__:unifi_db_pass', true) }}"
    MONGO_DBNAME: "unifi-db"
    MONGO_AUTHSOURCE: "admin"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: unifi_db_root_pass
        path: "/Unifi"
        name: DB_ROOT_PASS
        docker_secret: unifi_db_root_pass_secret
      - var: unifi_db_user
        path: "/Unifi"
        name: DB_USER
      - var: unifi_db_pass
        path: "/Unifi"
        name: DB_PASS
  secrets:
    - unifi_root_pass_secret
  paths:
    - path: /opt/unifi
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
    - path: /opt/unifi/db
      state: directory
      owner: 1000
      group: 1000
      mode: "0755"
  swarm_configs:
    - name: unifi-init-mongo.sh
      src: files/unifi-init-mongo.sh
      data_is_template: false
  configs:
    - source: unifi-init-mongo.sh
      target: /docker-entrypoint-initdb.d/init-mongo.sh
      mode: "0444"
  volumes:
    data:
      type: bind
      source: /opt/unifi/db
      target: /data/db
      read_only: false
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: localhost
    constraints:
      - node.labels.ansible_host == localhost
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
