---

unpackerr:
  name: unpackerr
  stack: unpackerr
  image: ghcr.io/hotio/unpackerr:release-0.14.5
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    PUID: "99"
    PGID: "100"
    UMASK: "022"
    UN_WEBSERVER_METRICS: "true"
    UN_WEBSERVER_UPSTREAMS: "172.98.0.0/24"
    ## Lidarr Settings
    UN_LIDARR_0_URL: "http://lidarr:8686"
    FILE__UN_LIDARR_0_API_KEY: /run/secrets/lidarr_api_secret
    UN_LIDARR_0_PATHS_0: "/data/torrents/completed"
    ## Radarr Settings
    UN_RADARR_0_URL: "http://radarr:7878"
    FILE__UN_RADARR_0_API_KEY: /run/secrets/radarr_api_secret
    UN_RADARR_0_PATHS_0: "/data/torrents/completed"
    UN_RADARR_1_URL: "http://radarr-4k:7878"
    FILE__UN_RADARR_1_API_KEY: /run/secrets/radarr_4k_api_secret
    UN_RADARR_1_PATHS_1: "/data/torrents/completed"
    ## Sonarr Settings
    UN_SONARR_0_URL: "http://sonarr:8989"
    FILE__UN_SONARR_0_API_KEY: /run/secrets/sonarr_api_secret
    UN_SONARR_0_PATHS_0: "/data/torrents/completed"
    UN_SONARR_1_URL: "http://sonarr-4k:8989"
    FILE__UN_SONARR_1_API_KEY: /run/secrets/sonarr_4k_api_secret
    UN_SONARR_1_PATHS_1: "/data/torrents/completed"
    ## Whisparr Settings
    UN_WHISPARR_0_URL: "http://whisparr:6969"
    UN_WHISPARR_0_API_KEY: /run/secrets/whisparr_api_secret
    UN_WHISPARR_0_PATHS_0: "/data/torrents/completed"
    ## Webhook Settings
    UN_WEBHOOK_0_URL: /run/secrets/unpackerr_webhook_secret
    UN_WEBHOOK_0_NAME: "Notifiarr"
  infisical:
    fail_on_empty: true
    secrets_map:
      - var: unpackerr_notifiarr_webhook
        path: "/Unpackerr"
        name: NOTIFIARR_WEBHOOK
        docker_secret: unpackerr_webhook_secret
      - var: lidarr_api
        path: "/Lidarr"
        name: API
        docker_secret: lidarr_api_secret
      - var: radarr_api
        path: "/Radarr"
        name: API
        docker_secret: radarr_api_secret
      - var: radarr_4k_api
        path: "/Radarr-4K"
        name: API
        docker_secret: radarr_4k_api_secret
      - var: sonarr_api
        path: "/Sonarr"
        name: API
        docker_secret: sonarr_api_secret
      - var: sonarr_4k_api
        path: "/Sonarr-4K"
        name: API
        docker_secret: sonarr_4k_api_secret
      - var: whisparr_api
        path: "/Whisparr"
        name: API
        docker_secret: whisparr_api_secret
  secrets:
    - lidarr_api_secret
    - radarr_api_secret
    - radarr_4k_api_secret
    - sonarr_api_secret
    - sonarr_4k_api_secret
    - whisparr_api_secret
    - unpackerr_webhook_secret
  volumes:
    media:
      type: bind
      source: /mnt/user/data
      target: /data
      read_only: false
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: unraid
    constraints:
      - node.labels.ansible_host == unraid
