---

znc:
  name: znc
  stack: znc
  image: lscr.io/linuxserver/znc:znc-1.10.1-ls177
  named_networks:
    overlay:
      external: true
  environment:
    TZ: "{{ timezone }}"
    PUID: "{{ hostvars['mgt'].docker_host_puid | string }}"
    PGID: "{{ hostvars['mgt'].docker_host_pgid | string }}"
    UMASK: "022"
  paths:
    - path: "{{ hostvars['mgt'].docker_host_appdata_root }}/znc"
      state: directory
      mode: "0755"
  volumes:
    config:
      type: bind
      source: "{{ hostvars['mgt'].docker_host_appdata_root }}/znc"
      target: /config
      read_only: false
  traefik:
    enable: true
    port: 6501
    sso: authelia
    internal_api: true
    internal_api_rules:
      - "PathPrefix(`/uploads`)"
  cloudflare:
    enable: true
  deploy:
    type: swarm
    mode: replicated
    replicas: 1
    host: mgt
    constraints:
      - node.labels.ansible_host == mgt
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 5
      window: 2m
