---

- name: Install Docker
  when: inventory_hostname != "unraid"
  ansible.builtin.include_tasks:
    file: _install.yml
    apply:
      tags:
        - docker
        - docker_install
  tags:
    - docker
    - docker_install

- name: Configure Docker Swarm
  ansible.builtin.include_tasks:
    file: _swarm.yml
    apply:
      tags:
        - docker
        - docker_swarm
  tags:
    - docker
    - docker_swarm
    - docker_swarm_init
    - docker_swarm_join
    - docker_swarm_network

- name: Docker Prune
  ansible.builtin.include_tasks:
    file: _prune.yml
    apply:
      tags:
        - docker
        - docker_prune
  tags:
    - docker
    - docker_prune
    - docker_prune_dangling
    - docker_prune_unused
    - docker_prune_volumes
