---

puid: 1000
pgid: 1000

local_ip: 192.168.80.45

ubuntu_ansible_root: /
ubuntu_ansible_repo_dirname: ansible
ubuntu_ansible_repo_path: "{{ ubuntu_ansible_root }}/{{ ubuntu_ansible_repo_dirname }}"

ubuntu_manage_repo_clone: true

docker_manage_user: true
docker_user: "swarm"

docker_swarm_hostname: "swarm"

docker_swarm_node_labels:
  role: manager
  ansible_host: localhost
