---

puid: 1000
pgid: 1000

local_ip: 192.168.80.48

docker_manage_user: true
docker_user: "mgt"
docker_swarm_hostname: "mgt"

docker_host_puid: 1000
docker_host_pgid: 1000
docker_host_appdata_root: /opt

docker_swarm_node_labels:
  role: manager
  ansible_host: mgt
  haproxy: "true"
  dns: technitium
