---

- name: Install postgres packages
  ansible.builtin.include_tasks:
    file: sub_tasks/apt.yml
    apply:
      tags:
        - postgres
        - postgres_apt
  tags:
    - postgres
    - postgres_apt

- name: Configure etcd
  ansible.builtin.include_tasks:
    file: sub_tasks/etcd.yml
    apply:
      tags:
        - postgres
        - postgres_etcd
  tags:
    - postgres
    - postgres_etcd

- name: Configure Patroni
  ansible.builtin.include_tasks:
    file: sub_tasks/patroni.yml
    apply:
      tags:
        - postgres
        - postgres_patroni
  tags:
    - postgres
    - postgres_patroni

- name: Ensure dedicated PostgreSQL admin role exists
  ansible.builtin.include_tasks:
    file: sub_tasks/pg_admin.yml
    apply:
      tags:
        - postgres
        - postgres_admin
  tags:
    - postgres
    - postgres_admin
