import importlib.util
from pathlib import Path

import pytest
from ansible.errors import AnsibleFilterError
from jinja2 import Environment, FileSystemLoader

TEMPLATE_DIR = Path(__file__).resolve().parents[2] / "ansible" / "roles" / "podman_services" / "templates"
FILTER_PATH = Path(__file__).resolve().parents[2] / "ansible" / "roles" / "podman_services" / "filter_plugins" / "podman_services.py"
COMMON_FILTER_PATH = Path(__file__).resolve().parents[2] / "ansible" / "roles" / "service_common" / "filter_plugins" / "service_common.py"
filter_spec = importlib.util.spec_from_file_location("podman_services", FILTER_PATH)
podman_services_filters = importlib.util.module_from_spec(filter_spec)
filter_spec.loader.exec_module(podman_services_filters)
common_filter_spec = importlib.util.spec_from_file_location("service_common", COMMON_FILTER_PATH)
service_common_filters = importlib.util.module_from_spec(common_filter_spec)
common_filter_spec.loader.exec_module(service_common_filters)


def render(name, service):
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), trim_blocks=True, lstrip_blocks=True)
    env.filters["podman_env_file_key"] = podman_services_filters.podman_env_file_key
    env.filters["podman_env_file_value"] = podman_services_filters.podman_env_file_value
    return env.get_template(name).render(
        podman_service=service,
        podman_services_quadlet_dir="/etc/containers/systemd",
    )


def service():
    return {
        "name": "n8n",
        "unit_name": "n8n",
        "description": "n8n",
        "image": "docker.io/n8nio/n8n:2.31.4",
        "network": {"name": "n8n", "driver": "bridge", "delete_on_stop": True},
        "volumes": [{"name": "n8n-data", "target": "/home/node/.n8n"}],
        "env": {
            "DB_TYPE": "postgresdb",
            "N8N_ENCRYPTION_KEY_FILE": "/run/secrets/n8n_encryption_key_secret",
            "NODES_EXCLUDE": '["n8n-nodes-base.executeCommand","n8n-nodes-base.readWriteFile"]',
        },
        "secrets": [
            {
                "name": "postgres_pass_secret",
                "uid": "1000",
                "gid": "1000",
                "mode": "0400",
                "value": "super-secret-value",
            },
            {"name": "n8n_encryption_key_secret", "uid": "1000", "gid": "1000", "mode": "0400"},
        ],
        "container": {
            "uid": "1000",
            "gid": "1000",
            "ports": [{"host_ip": "192.0.2.98", "host": 5678, "container": 5678, "protocol": "tcp"}],
            "mounts": [{"source": "/opt/n8n", "target": "/home/node/.n8n"}],
            "tmpfs": [{"target": "/tmp", "options": ["size=1048576", "mode=1777"]}],
            "cap_add": ["NET_BIND_SERVICE"],
            "cap_drop": ["all"],
            "no_new_privileges": True,
            "healthcheck": {"command": "node -e ok"},
            "systemd": {"after": ["custom-online.target"]},
        },
    }


def canonical_service():
    return {
        "runtime": "podman",
        "description": "Canonical portable service",
        "image": "ghcr.io/example/portable:1.2.3",
        "user": "1001:1002",
        "environment": {"APP_ENV": "production"},
        "deploy": {"type": "swarm", "mode": "replicated", "replicas": 1, "host": "podman01"},
        "ports": {
            "web": {
                "published": 8443,
                "target": 8080,
                "protocol": "tcp",
                "host_ip": "192.0.2.10",
            }
        },
        "volumes": {
            "config": {
                "type": "bind",
                "source": "/opt/portable/config",
                "target": "/config",
                "read_only": True,
            },
            "data": {
                "type": "volume",
                "source": "portable-data",
                "target": "/data",
                "read_only": False,
            },
            "scratch": {
                "type": "tmpfs",
                "target": "/tmp",
                "tmpfs": {"size": 1048576, "mode": 1777},
            },
        },
        "paths": [{"path": "/opt/portable/config"}],
        "cap_add": ["NET_BIND_SERVICE"],
        "cap_drop": ["ALL"],
        "no_new_privileges": True,
        "read_only": True,
        "healthcheck": {
            "test": ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/health"],
            "interval": "20s",
            "timeout": "5s",
            "retries": 4,
            "start_period": "30s",
        },
        "runtime_options": {
            "podman": {
                "network": {"name": "portable", "driver": "bridge", "delete_on_stop": True},
            }
        },
    }


def test_container_quadlet_is_deterministic_and_secret_safe():
    first = render("container.container.j2", service())
    second = render("container.container.j2", service())
    assert first == second
    assert "# Generated by Ansible" in first
    assert "Image=docker.io/n8nio/n8n:2.31.4" in first
    assert "Secret=n8n_encryption_key_secret,target=/run/secrets/n8n_encryption_key_secret,uid=1000,gid=1000,mode=0400" in first
    assert "super-secret-value" not in first
    assert "User=1000" in first
    assert "Group=1000" in first
    assert "User=1000:1000" not in first
    assert "NoNewPrivileges=true" in first
    assert "PodmanArgs=--security-opt=no-new-privileges" not in first
    assert "AddCapability=NET_BIND_SERVICE" in first
    assert "DropCapability=all" in first
    assert "Tmpfs=/tmp:size=1048576,mode=1777" in first
    assert "Volume=n8n-data.volume:/home/node/.n8n" in first
    assert "PublishPort=192.0.2.98:5678:5678/tcp" in first
    assert "After=custom-online.target" in first
    assert "WantedBy=multi-user.target" in first


def test_canonical_normalization_reaches_container_quadlet():
    normalized = podman_services_filters.podman_service_normalize(canonical_service(), "portable")
    rendered = render("container.container.j2", normalized)

    assert "Image=ghcr.io/example/portable:1.2.3" in rendered
    assert "User=1001" in rendered
    assert "Group=1002" in rendered
    assert "EnvironmentFile=/etc/containers/systemd/portable.env" in rendered
    assert "Network=portable.network" in rendered
    assert "PublishPort=192.0.2.10:8443:8080/tcp" in rendered
    assert "Volume=portable-data.volume:/data" in rendered
    assert "Volume=/opt/portable/config:/config:ro" in rendered
    assert "Tmpfs=/tmp:size=1048576,mode=1777" in rendered
    assert "AddCapability=NET_BIND_SERVICE" in rendered
    assert "DropCapability=ALL" in rendered
    assert "NoNewPrivileges=true" in rendered
    assert "ReadOnly=true" in rendered
    assert "HealthCmd=curl -fsS http://127.0.0.1:8080/health" in rendered
    assert "HealthInterval=20s" in rendered
    assert "HealthTimeout=5s" in rendered
    assert "HealthRetries=4" in rendered
    assert "HealthStartPeriod=30s" in rendered
    expected_lines = {
        "Image=ghcr.io/example/portable:1.2.3",
        "User=1001",
        "Group=1002",
        "EnvironmentFile=/etc/containers/systemd/portable.env",
        "Network=portable.network",
        "PublishPort=192.0.2.10:8443:8080/tcp",
        "Volume=portable-data.volume:/data",
        "Volume=/opt/portable/config:/config:ro",
        "Tmpfs=/tmp:size=1048576,mode=1777",
        "AddCapability=NET_BIND_SERVICE",
        "DropCapability=ALL",
        "NoNewPrivileges=true",
        "ReadOnly=true",
        "HealthCmd=curl -fsS http://127.0.0.1:8080/health",
        "HealthInterval=20s",
        "HealthTimeout=5s",
        "HealthRetries=4",
        "HealthStartPeriod=30s",
    }
    assert expected_lines <= set(rendered.splitlines())


def test_no_new_privileges_false_is_not_rendered():
    svc = service()
    svc["container"]["no_new_privileges"] = False

    rendered = render("container.container.j2", svc)

    assert "NoNewPrivileges=true" not in rendered


def test_network_quadlet_is_deterministic():
    rendered = render("network.network.j2", service())
    assert rendered == render("network.network.j2", service())
    assert "NetworkName=n8n" in rendered
    assert "Driver=bridge" in rendered
    assert "NetworkDeleteOnStop=true" in rendered


@pytest.mark.parametrize(
    ("value", "expected"),
    [
        ('["node-a","node-b"]', '["node-a","node-b"]'),
        ("value with spaces", "value with spaces"),
        ("left=right=again", "left=right=again"),
        (True, "true"),
        (False, "false"),
        (42, "42"),
        ("", ""),
        ("single'quote", "single'quote"),
        ('double"quote', 'double"quote'),
        (None, ""),
    ],
)
def test_env_file_value_serializes_supported_scalars_without_shell_quotes(value, expected):
    assert podman_services_filters.podman_env_file_value(value) == expected


@pytest.mark.parametrize("value", ["line\nbreak", "carriage\rreturn", "nul\0byte"])
def test_env_file_value_rejects_line_injection(value):
    with pytest.raises(AnsibleFilterError, match="must not contain"):
        podman_services_filters.podman_env_file_value(value)


@pytest.mark.parametrize("value", [{"nested": "mapping"}, ["a", "list"], 1.5])
def test_env_file_value_rejects_complex_or_unsupported_values(value):
    with pytest.raises(AnsibleFilterError, match="serialize structured"):
        podman_services_filters.podman_env_file_value(value)


@pytest.mark.parametrize("key", ["1INVALID", "HAS-DASH", "HAS.DOT", "", 42])
def test_env_file_key_rejects_invalid_names(key):
    with pytest.raises(AnsibleFilterError, match="env-file key"):
        podman_services_filters.podman_env_file_key(key)


def test_env_file_renders_json_and_literal_content_without_shell_quotes():
    svc = service()
    quote_value = 'single\' and "double"'
    svc["env"].update(
        {
            "SPACE": "two words",
            "EQUALS": "left=right",
            "BOOL": False,
            "INTEGER": 7,
            "EMPTY": "",
            "QUOTES": quote_value,
            "NULL_VALUE": None,
        }
    )

    rendered = render("env.env.j2", svc)

    assert 'NODES_EXCLUDE=["n8n-nodes-base.executeCommand","n8n-nodes-base.readWriteFile"]' in rendered
    assert "SPACE=two words" in rendered
    assert "EQUALS=left=right" in rendered
    assert "BOOL=false" in rendered
    assert "INTEGER=7" in rendered
    assert "EMPTY=\n" in rendered
    assert f"QUOTES={quote_value}" in rendered
    assert "NULL_VALUE=\n" in rendered
    assert "N8N_ENCRYPTION_KEY_FILE=/run/secrets/n8n_encryption_key_secret" in rendered
    assert "super-secret-value" not in rendered


def test_volume_quadlet_is_deterministic():
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), trim_blocks=True, lstrip_blocks=True)
    template = env.get_template("volume.volume.j2")
    volume = {"name": "n8n-data"}
    rendered = template.render(volume=volume)
    assert rendered == template.render(volume=volume)
    assert "VolumeName=n8n-data" in rendered


def test_container_quadlet_default_port_binding():
    svc = service()
    del svc["container"]["ports"][0]["host_ip"]
    rendered = render("container.container.j2", svc)
    assert "PublishPort=5678:5678/tcp" in rendered
    assert "PublishPort=192.0.2.98:5678:5678/tcp" not in rendered


def test_generic_network_does_not_default_delete_on_stop():
    svc = service()
    del svc["network"]["delete_on_stop"]
    rendered = render("network.network.j2", svc)
    assert "NetworkDeleteOnStop=true" not in rendered


def test_container_quadlet_has_no_manual_default_network_dependency():
    svc = service()
    del svc["container"]["systemd"]
    rendered = render("container.container.j2", svc)
    assert "After=network-online.target" not in rendered
    assert "Wants=network-online.target" not in rendered
    assert "Restart=on-failure" in rendered
    assert "RestartSec=15s" in rendered


def test_container_quadlet_renders_explicit_custom_after_dependencies():
    svc = service()
    svc["container"]["systemd"]["after"] = ["postgresql.service", "custom-online.target"]

    rendered = render("container.container.j2", svc)

    assert "After=postgresql.service" in rendered
    assert "After=custom-online.target" in rendered


def test_canonical_secret_normalization_reaches_quadlet_without_value():
    cfg = canonical_service()
    cfg["infisical"] = {
        "secrets_map": [
            {
                "var": "app_secret_value",
                "path": "/Portable",
                "name": "VALUE",
                "secret": {
                    "name": "app_secret",
                    "target": "/run/secrets/app_secret",
                    "uid": "1001",
                    "gid": "1002",
                    "mode": "0400",
                    "runtime_options": {
                        "podman": {
                            "immutable": True,
                            "replace": False,
                        }
                    },
                },
            }
        ]
    }

    normalized = podman_services_filters.podman_service_normalize(cfg, "portable")
    common = service_common_filters.service_common_infisical_normalize(cfg["infisical"]["secrets_map"])
    normalized["secrets"] = podman_services_filters.podman_secret_declarations(common["secret_declarations"])
    rendered = render("container.container.j2", normalized)

    assert "Secret=app_secret,target=/run/secrets/app_secret,uid=1001,gid=1002,mode=0400" in rendered
    assert "app_secret_value" not in rendered
    assert "VALUE" not in rendered
