import importlib.util
import tomllib
from pathlib import Path

import pytest
from ansible.errors import AnsibleFilterError
from jinja2 import Environment, FileSystemLoader, StrictUndefined

REPO_ROOT = Path(__file__).resolve().parents[2]
ROLE_ROOT = REPO_ROOT / "ansible/roles/podman_services"
MODULE_PATH = ROLE_ROOT / "filter_plugins/podman_services.py"
spec = importlib.util.spec_from_file_location("podman_services_rootless_network", MODULE_PATH)
podman_services = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(podman_services)


def test_rootless_pasta_configuration_uses_the_documented_private_ipv4_shape():
    config = podman_services.podman_rootless_pasta_config("10.0.2.0/24", "10.0.2.2", "10.0.2.3")

    assert config == {
        "subnet": "10.0.2.0/24",
        "address": "10.0.2.0",
        "prefix_length": 24,
        "gateway": "10.0.2.2",
        "dns_forward": "10.0.2.3",
        "options": [
            "--ipv4-only",
            "-a",
            "10.0.2.0",
            "-n",
            "24",
            "-g",
            "10.0.2.2",
            "--dns-forward",
            "10.0.2.3",
            "--no-ndp",
            "--no-dhcpv6",
            "--no-dhcp",
        ],
    }


def test_rootless_pasta_dropin_renders_valid_toml_with_exact_options():
    config = podman_services.podman_rootless_pasta_config("10.0.2.0/24", "10.0.2.2", "10.0.2.3")
    rendered = (
        Environment(loader=FileSystemLoader(ROLE_ROOT / "templates"), undefined=StrictUndefined)
        .get_template("rootless-network.conf.j2")
        .render(podman_services_rootless_pasta_config=config)
    )

    assert rendered.startswith("# Generated by Ansible. Do not edit manually.\n[network]\n")
    assert tomllib.loads(rendered)["network"]["pasta_options"] == config["options"]


@pytest.mark.parametrize(
    ("subnet", "gateway", "dns_forward", "message"),
    [
        ("10.0.2.1/24", "10.0.2.2", "10.0.2.3", "host bits set"),
        ("203.0.113.0/24", "203.0.113.2", "203.0.113.3", "RFC 1918"),
        ("2001:db8::/64", "2001:db8::2", "2001:db8::3", "must be IPv4"),
        ("10.0.2.0/24", "10.0.3.2", "10.0.2.3", "gateway must be a usable address"),
        ("10.0.2.0/24", "10.0.2.0", "10.0.2.3", "gateway must be a usable address"),
        ("10.0.2.0/24", "10.0.2.2", "10.0.2.255", "DNS forwarder must be a usable address"),
        ("10.0.2.0/31", "10.0.2.0", "10.0.2.1", "must provide usable"),
        ("10.0.2.0/24", "10.0.2.2", "10.0.2.2", "must be distinct"),
        (" 10.0.2.0/24", "10.0.2.2", "10.0.2.3", "trimmed strings"),
    ],
)
def test_rootless_pasta_configuration_rejects_incoherent_values(subnet, gateway, dns_forward, message):
    with pytest.raises(AnsibleFilterError, match=message):
        podman_services.podman_rootless_pasta_config(subnet, gateway, dns_forward)


def test_rootless_pasta_route_overlap_ignores_default_and_accepts_unrelated_routes():
    routes = [
        {"dst": "default", "gateway": "192.168.80.1"},
        {"dst": "192.168.80.0/24", "dev": "ens18"},
        {"dst": "172.98.0.0/24", "dev": "docker_gwbridge"},
    ]

    assert podman_services.podman_rootless_pasta_route_overlaps(routes, "10.0.2.0/24") == []


@pytest.mark.parametrize(
    ("destination", "expected"),
    [
        ("10.0.2.0/24", ["10.0.2.0/24"]),
        ("10.0.0.0/8", ["10.0.0.0/8"]),
        ("10.0.2.42", ["10.0.2.42/32"]),
    ],
)
def test_rootless_pasta_route_overlap_rejects_direct_or_reachable_conflicts(destination, expected):
    assert podman_services.podman_rootless_pasta_route_overlaps([{"dst": destination}], "10.0.2.0/24") == expected


@pytest.mark.parametrize("routes", ["invalid", {}, [{"dst": "not-a-route"}], ["not-a-mapping"]])
def test_rootless_pasta_route_overlap_fails_closed_on_invalid_route_data(routes):
    with pytest.raises(AnsibleFilterError, match="Host IPv4 route"):
        podman_services.podman_rootless_pasta_route_overlaps(routes, "10.0.2.0/24")
