import importlib.util
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

TEMPLATE_DIR = Path(__file__).resolve().parents[2] / "ansible" / "roles" / "podman_services" / "templates"
FILTER_PATH = Path(__file__).resolve().parents[2] / "ansible" / "roles" / "podman_services" / "filter_plugins" / "podman_services.py"
filter_spec = importlib.util.spec_from_file_location("podman_services", FILTER_PATH)
podman_services_filters = importlib.util.module_from_spec(filter_spec)
filter_spec.loader.exec_module(podman_services_filters)


def render(name, service):
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), trim_blocks=True, lstrip_blocks=True)
    env.filters["podman_env_quote"] = podman_services_filters.podman_env_quote
    return env.get_template(name).render(podman_service=service, internal_zone="int.example.test")


def service():
    return {
        "name": "n8n",
        "unit_name": "n8n",
        "description": "n8n",
        "image": "docker.io/n8nio/n8n:2.31.4",
        "network": {"name": "n8n", "driver": "bridge", "delete_on_stop": True},
        "volumes": [{"name": "n8n-data", "target": "/home/node/.n8n"}],
        "env": {
            "DB_TYPE": "postgresdb",
            "N8N_ENCRYPTION_KEY_FILE": "/run/secrets/n8n_encryption_key_secret",
            "NODES_EXCLUDE": '["n8n-nodes-base.executeCommand","n8n-nodes-base.readWriteFile"]',
        },
        "secrets": [
            {"name": "postgres_pass_secret", "uid": "1000", "gid": "1000", "mode": "0400"},
            {"name": "n8n_encryption_key_secret", "uid": "1000", "gid": "1000", "mode": "0400"},
        ],
        "container": {
            "uid": "1000",
            "gid": "1000",
            "ports": [{"host_ip": "192.0.2.98", "host": 5678, "container": 5678, "protocol": "tcp"}],
            "mounts": [{"source": "/opt/n8n", "target": "/home/node/.n8n"}],
            "cap_drop": ["all"],
            "no_new_privileges": True,
            "healthcheck": {"command": "node -e ok"},
            "systemd": {"after": ["network-online.target"]},
        },
    }


def test_container_quadlet_is_deterministic_and_secret_safe():
    first = render("container.container.j2", service())
    second = render("container.container.j2", service())
    assert first == second
    assert "# Generated by Ansible" in first
    assert "Image=docker.io/n8nio/n8n:2.31.4" in first
    assert "Secret=n8n_encryption_key_secret,target=/run/secrets/n8n_encryption_key_secret,uid=1000,gid=1000,mode=0400" in first
    assert "super-secret-value" not in first
    assert "User=1000" in first
    assert "Group=1000" in first
    assert "User=1000:1000" not in first
    assert "NoNewPrivileges=true" in first
    assert "PodmanArgs=--security-opt=no-new-privileges" not in first
    assert "DropCapability=all" in first
    assert "Volume=n8n-data.volume:/home/node/.n8n" in first
    assert "PublishPort=192.0.2.98:5678:5678/tcp" in first


def test_network_quadlet_is_deterministic():
    rendered = render("network.network.j2", service())
    assert rendered == render("network.network.j2", service())
    assert "NetworkName=n8n" in rendered
    assert "Driver=bridge" in rendered
    assert "NetworkDeleteOnStop=true" in rendered


def test_env_file_quotes_json_values():
    rendered = render("env.env.j2", service())
    assert "N8N_ENCRYPTION_KEY_FILE=/run/secrets/n8n_encryption_key_secret" in rendered
    assert "DB_TYPE=postgresdb" in rendered
    assert 'NODES_EXCLUDE=\'["n8n-nodes-base.executeCommand","n8n-nodes-base.readWriteFile"]\'' in rendered


def test_volume_quadlet_is_deterministic():
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), trim_blocks=True, lstrip_blocks=True)
    template = env.get_template("volume.volume.j2")
    volume = {"name": "n8n-data"}
    rendered = template.render(volume=volume)
    assert rendered == template.render(volume=volume)
    assert "VolumeName=n8n-data" in rendered


def test_container_quadlet_default_port_binding():
    svc = service()
    del svc["container"]["ports"][0]["host_ip"]
    rendered = render("container.container.j2", svc)
    assert "PublishPort=5678:5678/tcp" in rendered
    assert "PublishPort=192.0.2.98:5678:5678/tcp" not in rendered


def test_generic_network_does_not_default_delete_on_stop():
    svc = service()
    del svc["network"]["delete_on_stop"]
    rendered = render("network.network.j2", svc)
    assert "NetworkDeleteOnStop=true" not in rendered


def test_container_quadlet_defaults_when_systemd_mapping_absent():
    svc = service()
    del svc["container"]["systemd"]
    rendered = render("container.container.j2", svc)
    assert "After=network-online.target" in rendered
    assert "Restart=on-failure" in rendered
    assert "RestartSec=15s" in rendered
