---

################################
# SERVICE PREP (MISC)
################################

- name: Prep | Plex (claims/token/etc)
  when:
    - inventory_hostname == docker_services_primary_manager
    - (docker_services_svc.name | default('') | string | trim) == "plex"
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/services/plex/tasker.yml"
    apply:
      tags: [deploy, bootstrap, recreate]
  run_once: true
  tags: [deploy, bootstrap, recreate]

- name: Prep | Bazarr
  when:
    - inventory_hostname == docker_services_primary_manager
    - docker_services_svc.name  | default('') == "bazarr"
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/services/bazarr.yml"
    apply:
      tags: [deploy, update, recreate]
  run_once: true
  tags: [deploy, update, recreate]

- name: Prep | Hugo (blog)
  when:
    - inventory_hostname == docker_services_primary_manager
    - (docker_services_svc.name | default('') | string | trim) == "hugo"
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/services/hugo.yml"
    apply:
      tags: [deploy, bootstrap, recreate]
  run_once: true
  tags: [deploy, bootstrap, recreate]

- name: Prep | NZBHydra2
  when:
    - inventory_hostname == docker_services_primary_manager
    - docker_services_svc.name  | default('') == "nzbhydra2"
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/services/nzbhydra2.yml"
    apply:
      tags: [deploy, update, recreate]
  run_once: true
  tags: [deploy, update, recreate]

- name: Prep | Vaultwarden
  when:
    - inventory_hostname == docker_services_primary_manager
    - docker_services_svc.name == "vaultwarden"
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/services/vaultwarden.yml"
    apply:
      tags: [deploy, update, recreate]
  run_once: true
  tags: [deploy, update, recreate]
