---

name: OpenTofu Docs

on:
  pull_request:
    paths:
      - "terraform/**/*.tf"
      - ".github/workflows/tofu-docs.yml"
  push:
    branches:
      - main
    paths:
      - "terraform/**/*.tf"
      - ".github/workflows/tofu-docs.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        root:
          - terraform/proxmox/mappings/resources
          - terraform/proxmox/settings/pve1
          - terraform/proxmox/templates/ubuntu-2404
          - terraform/proxmox/vms/postgres-cluster
          - terraform/proxmox/vms/unraid

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Render terraform docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ${{ matrix.root }}
          output-file: README.md
          output-method: inject
          git-push: "true"
