---

name: OpenTofu Docs

on:
  pull_request:
    paths:
      - "terraform/**/*.tf"
      - ".github/workflows/tofu-docs.yml"
  push:
    branches:
      - main
    paths:
      - "terraform/**/*.tf"
      - ".github/workflows/tofu-docs.yml"

concurrency:
  group: tofu-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Render OpenTofu docs
        uses: terraform-docs/gh-actions@90d7d172a97c5c65dfdb856ffdc7ba13e7d30d4d
        with:
          working-dir: .
          find-dir: terraform
          recursive: true
          recursive-path: .
          output-file: README.md
          output-method: inject
          git-push: "true"
