---

- name: Deploy - Config | Ensure docker_services_service_name is set
  ansible.builtin.assert:
    that:
      - docker_services_service_name is defined
      - docker_services_service_name | string | trim | length > 0
    fail_msg: "docker_services_service_name must be set before calling this helper"

- name: Deploy - Config | Build deploy dict
  ansible.builtin.set_fact:
    docker_services_deploy_dict: >-
      {{
        docker_services_svc.deploy | default({}, true)
        | docker_services_build_deploy_config(
            mode=deploy_mode | default(none, true),
            replicas=deploy_replicas | default(none, true),
            constraints=deploy_constraints | default(none, true),
            profile=deploy_profile | default(none, true),
            service_profile=docker_services_svc.deploy.profile | default(none, true),
            default_profile=docker_services_default_deploy_profile | default('none', true),
            profiles=docker_services_deploy_profiles | default({'none': {}}, true),
            restart_policy=deploy_restart_policy | default(none, true),
            update_config=deploy_update_config | default(none, true),
            rollback_config=deploy_rollback_config | default(none, true),
            resources=deploy_resources | default(none, true)
          )
      }}

- name: Deploy - Config | Attach deploy config to service
  ansible.builtin.set_fact:
    docker_services_compose_services: >-
      {{
        (docker_services_compose_services | default({}))
        | combine({
            docker_services_service_name: (
              ((docker_services_compose_services | default({})).get(docker_services_service_name, {}))
              | combine({ 'deploy': docker_services_deploy_dict }, recursive=true)
            )
          }, recursive=true)
      }}
